declare module "packages/moe/wolfgirl/probejs/generated/TagEventProbe" {
	import { $TagWrapper } from "packages/dev/latvian/mods/kubejs/server/tag/$TagWrapper";
	import { TagWrapperProbe } from "packages/moe/wolfgirl/probejs/generated/TagWrapperProbe";
	import { $TagEventJS } from "packages/dev/latvian/mods/kubejs/server/tag/$TagEventJS";

	/**
	 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
	 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
	 * Loading the class will not throw an error, but instead the class loaded will be undefined.
	 */
	export class TagEventProbe<T, I> extends $TagEventJS {
		public add(tag: T | string, filters: (I | string)[]): TagWrapperProbe<T, I>;
		public add(tag: T | string, filters: I | string): TagWrapperProbe<T, I>;
		public remove(
			tag: T | string,
			filters: (I | string)[]
		): TagWrapperProbe<T, I>;
		public remove(tag: T | string, filters: I | string): TagWrapperProbe<T, I>;
	}
	/**
	 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
	 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
	 * Loading the class will not throw an error, but instead the class loaded will be undefined.
	 */
	export class TagWrapperProbe<T, I> extends $TagWrapper {
		public add(filters: (I | string)[]): this;
		public remove(filters: (I | string)[]): this;
	}
	/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
	export type TagEventProbe$$Type<T, I> = TagEventProbe<T, I>;
	/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
	declare global {
		export type TagEventProbe_<T, I> = TagEventProbe$$Type<T, I>;
	}
}
