declare module "packages/net/minecraft/world/entity/npc/$VillagerType" {
import { $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Biome, $Biome$$Type } from "packages/net/minecraft/world/level/biome/$Biome"
import { $ResourceKey, $ResourceKey$$Type } from "packages/net/minecraft/resources/$ResourceKey"
import { $Map } from "packages/java/util/$Map"

export class $VillagerType {
static "BY_BIOME": $Map<$ResourceKey<$Biome>, $VillagerType>
static readonly "DESERT": $VillagerType
static readonly "JUNGLE": $VillagerType
static readonly "PLAINS": $VillagerType
static readonly "SAVANNA": $VillagerType
static readonly "SNOW": $VillagerType
static readonly "SWAMP": $VillagerType
static readonly "TAIGA": $VillagerType

constructor(string0: string)

public static "byBiome"(holder0: $Holder$$Type<$Biome$$Type>): $VillagerType
public static "registerBiomeType"(resourceKey0: $ResourceKey$$Type<$Biome>, villagerType1: $VillagerType$$Type): void
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.VillagerType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.VillagerTypeTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VillagerType$$Type = ($VillagerType | Special.VillagerType);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VillagerType_ = $VillagerType$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$VillagerDataHolder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VillagerDataHolder$$Type = ($VillagerDataHolder);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VillagerDataHolder_ = $VillagerDataHolder$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$VillagerData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VillagerData$$Type = ($VillagerData);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VillagerData_ = $VillagerData$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$VillagerProfession" {
import { $ImmutableSet, $ImmutableSet$$Type } from "packages/com/google/common/collect/$ImmutableSet"
import { $Item, $Item$$Type } from "packages/net/minecraft/world/item/$Item"
import { $SoundEvent, $SoundEvent$$Type } from "packages/net/minecraft/sounds/$SoundEvent"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Record } from "packages/java/lang/$Record"
import { $Predicate, $Predicate$$Type } from "packages/java/util/function/$Predicate"
import { $PoiType, $PoiType$$Type } from "packages/net/minecraft/world/entity/ai/village/poi/$PoiType"
import { $Block, $Block$$Type } from "packages/net/minecraft/world/level/block/$Block"

export class $VillagerProfession extends $Record {
static readonly "ALL_ACQUIRABLE_JOBS": $Predicate<$Holder<$PoiType>>
static readonly "ARMORER": $VillagerProfession
static readonly "BUTCHER": $VillagerProfession
static readonly "CARTOGRAPHER": $VillagerProfession
static readonly "CLERIC": $VillagerProfession
static readonly "FARMER": $VillagerProfession
static readonly "FISHERMAN": $VillagerProfession
static readonly "FLETCHER": $VillagerProfession
static readonly "LEATHERWORKER": $VillagerProfession
static readonly "LIBRARIAN": $VillagerProfession
static readonly "MASON": $VillagerProfession
static readonly "NITWIT": $VillagerProfession
static readonly "NONE": $VillagerProfession
static readonly "SHEPHERD": $VillagerProfession
static readonly "TOOLSMITH": $VillagerProfession
static readonly "WEAPONSMITH": $VillagerProfession

constructor(string0: string, predicate1: $Predicate$$Type<$Holder$$Type<$PoiType$$Type>>, predicate2: $Predicate$$Type<$Holder$$Type<$PoiType$$Type>>, immutableSet3: $ImmutableSet$$Type<$Item$$Type>, immutableSet4: $ImmutableSet$$Type<$Block$$Type>, soundEvent5: $SoundEvent$$Type)

public "acquirableJobSite"(): $Predicate<$Holder<$PoiType>>
public "heldJobSite"(): $Predicate<$Holder<$PoiType>>
public "name"(): string
public "requestedItems"(): $ImmutableSet<$Item>
public "secondaryPoi"(): $ImmutableSet<$Block>
public "workSound"(): $SoundEvent
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.VillagerProfession
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.VillagerProfessionTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VillagerProfession$$Type = ($VillagerProfession | Special.VillagerProfession);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VillagerProfession_ = $VillagerProfession$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$WanderingTrader" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WanderingTrader$$Type = ($WanderingTrader);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WanderingTrader_ = $WanderingTrader$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$Npc" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Npc$$Type = ($Npc);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Npc_ = $Npc$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$VillagerTrades$ItemListing" {
import { $MerchantOffer$$Type } from "packages/net/minecraft/world/item/trading/$MerchantOffer"
import { $RandomSource } from "packages/net/minecraft/util/$RandomSource"
import { $Entity } from "packages/net/minecraft/world/entity/$Entity"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VillagerTrades$ItemListing$$Type = ($VillagerTrades$ItemListing | ((arg0: $Entity, arg1: $RandomSource) => $MerchantOffer$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VillagerTrades$ItemListing_ = $VillagerTrades$ItemListing$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$InventoryCarrier" {
import { $SimpleContainer$$Type } from "packages/net/minecraft/world/$SimpleContainer"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $InventoryCarrier$$Type = ($InventoryCarrier | (() => $SimpleContainer$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $InventoryCarrier_ = $InventoryCarrier$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$AbstractVillager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AbstractVillager$$Type = ($AbstractVillager);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AbstractVillager_ = $AbstractVillager$$Type;
}
}

declare module "packages/net/minecraft/world/entity/npc/$Villager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Villager$$Type = ($Villager);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Villager_ = $Villager$$Type;
}
}

