declare module "packages/net/minecraft/world/level/dimension/$DimensionType$MonsterSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DimensionType$MonsterSettings$$Type = ($DimensionType$MonsterSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DimensionType$MonsterSettings_ = $DimensionType$MonsterSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/dimension/$DimensionType" {
import { $DimensionType$MonsterSettings, $DimensionType$MonsterSettings$$Type } from "packages/net/minecraft/world/level/dimension/$DimensionType$MonsterSettings"
import { $Path, $Path$$Type } from "packages/java/nio/file/$Path"
import { $DimensionTypeAccessor } from "packages/net/irisshaders/iris/mixin/$DimensionTypeAccessor"
import { $Level } from "packages/net/minecraft/world/level/$Level"
import { $ResourceLocation, $ResourceLocation$$Type } from "packages/net/minecraft/resources/$ResourceLocation"
import { $TagKey, $TagKey$$Type } from "packages/net/minecraft/tags/$TagKey"
import { $Block, $Block$$Type } from "packages/net/minecraft/world/level/block/$Block"
import { $Dynamic$$Type } from "packages/com/mojang/serialization/$Dynamic"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $Record } from "packages/java/lang/$Record"
import { $DataResult } from "packages/com/mojang/serialization/$DataResult"
import { $OptionalLong, $OptionalLong$$Type } from "packages/java/util/$OptionalLong"
import { $IntProvider } from "packages/net/minecraft/util/valueproviders/$IntProvider"
import { $ResourceKey, $ResourceKey$$Type } from "packages/net/minecraft/resources/$ResourceKey"

export class $DimensionType extends $Record implements $DimensionTypeAccessor {
static readonly "BITS_FOR_Y": integer
static readonly "CODEC": $Codec<$Holder<$DimensionType>>
static readonly "DIRECT_CODEC": $Codec<$DimensionType>
static readonly "MAX_Y": integer
static readonly "MIN_HEIGHT": integer
static readonly "MIN_Y": integer
static readonly "MOON_BRIGHTNESS_PER_PHASE": float[]
static readonly "WAY_ABOVE_MAX_Y": integer
static readonly "WAY_BELOW_MIN_Y": integer
static readonly "Y_SIZE": integer

constructor(optionalLong0: $OptionalLong$$Type, boolean1: boolean, boolean2: boolean, boolean3: boolean, boolean4: boolean, double5: double, boolean6: boolean, boolean7: boolean, int8: integer, int9: integer, int10: integer, tagKey11: $TagKey$$Type<$Block$$Type>, resourceLocation12: $ResourceLocation$$Type, float13: float, monsterSettings14: $DimensionType$MonsterSettings$$Type)

public "ambientLight"(): float
public "bedWorks"(): boolean
public "coordinateScale"(): double
public "effectsLocation"(): $ResourceLocation
public "fixedTime"(): $OptionalLong
public static "getStorageFolder"(resourceKey0: $ResourceKey$$Type<$Level>, path1: $Path$$Type): $Path
public static "getTeleportationScale"(dimensionType0: $DimensionType$$Type, dimensionType1: $DimensionType$$Type): double
public "hasCeiling"(): boolean
public "hasFixedTime"(): boolean
public "hasRaids"(): boolean
public "hasSkyLight"(): boolean
public "height"(): integer
public "infiniburn"(): $TagKey<$Block>
public "logicalHeight"(): integer
public "minY"(): integer
public "monsterSettings"(): $DimensionType$MonsterSettings
public "monsterSpawnBlockLightLimit"(): integer
public "monsterSpawnLightTest"(): $IntProvider
public "moonPhase"(long0: long): integer
public "natural"(): boolean
/** @deprecated */
public static "parseLegacy"(dynamic0: $Dynamic$$Type<any>): $DataResult<$ResourceKey<$Level>>
public "piglinSafe"(): boolean
public "respawnAnchorWorks"(): boolean
public "timeOfDay"(long0: long): float
public "ultraWarm"(): boolean
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.DimensionType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.DimensionTypeTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DimensionType$$Type = ($DimensionType | Special.DimensionType);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DimensionType_ = $DimensionType$$Type;
}
}

declare module "packages/net/minecraft/world/level/dimension/end/$EndDragonFight$Data" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EndDragonFight$Data$$Type = ($EndDragonFight$Data);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EndDragonFight$Data_ = $EndDragonFight$Data$$Type;
}
}

declare module "packages/net/minecraft/world/level/dimension/$LevelStem" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LevelStem$$Type = ($LevelStem);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LevelStem_ = $LevelStem$$Type;
}
}

declare module "packages/net/minecraft/world/level/dimension/end/$EndDragonFight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EndDragonFight$$Type = ($EndDragonFight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EndDragonFight_ = $EndDragonFight$$Type;
}
}

