declare module "packages/net/minecraft/world/level/levelgen/carver/$CarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CarverConfiguration$$Type = ($CarverConfiguration);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CarverConfiguration_ = $CarverConfiguration$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$ConfiguredWorldCarver" {
import { $HolderSet } from "packages/net/minecraft/core/$HolderSet"
import { $ChunkPos$$Type } from "packages/net/minecraft/world/level/$ChunkPos"
import { $CarverConfiguration, $CarverConfiguration$$Type } from "packages/net/minecraft/world/level/levelgen/carver/$CarverConfiguration"
import { $ChunkAccess$$Type } from "packages/net/minecraft/world/level/chunk/$ChunkAccess"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $CarvingMask$$Type } from "packages/net/minecraft/world/level/chunk/$CarvingMask"
import { $WorldCarver, $WorldCarver$$Type } from "packages/net/minecraft/world/level/levelgen/carver/$WorldCarver"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $Function$$Type } from "packages/java/util/function/$Function"
import { $Record } from "packages/java/lang/$Record"
import { $Aquifer$$Type } from "packages/net/minecraft/world/level/levelgen/$Aquifer"
import { $Biome } from "packages/net/minecraft/world/level/biome/$Biome"
import { $RandomSource$$Type } from "packages/net/minecraft/util/$RandomSource"
import { $CarvingContext$$Type } from "packages/net/minecraft/world/level/levelgen/carver/$CarvingContext"
import { $BlockPos$$Type } from "packages/net/minecraft/core/$BlockPos"

export class $ConfiguredWorldCarver<WC extends $CarverConfiguration> extends $Record {
static readonly "CODEC": $Codec<$Holder<$ConfiguredWorldCarver<any>>>
static readonly "DIRECT_CODEC": $Codec<$ConfiguredWorldCarver<any>>
static readonly "LIST_CODEC": $Codec<$HolderSet<$ConfiguredWorldCarver<any>>>

constructor(worldCarver0: $WorldCarver$$Type<WC>, wc1: WC)

public "carve"(carvingContext0: $CarvingContext$$Type, chunkAccess1: $ChunkAccess$$Type, function2: $Function$$Type<$BlockPos$$Type, $Holder<$Biome>>, randomSource3: $RandomSource$$Type, aquifer4: $Aquifer$$Type, chunkPos5: $ChunkPos$$Type, carvingMask6: $CarvingMask$$Type): boolean
public "config"(): WC
public "isStartChunk"(randomSource0: $RandomSource$$Type): boolean
public "worldCarver"(): $WorldCarver<WC>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenConfiguredCarver
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenConfiguredCarverTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ConfiguredWorldCarver$$Type<WC extends $CarverConfiguration> = ($ConfiguredWorldCarver<WC> | Special.WorldgenConfiguredCarver);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ConfiguredWorldCarver_<WC extends $CarverConfiguration> = $ConfiguredWorldCarver$$Type<WC>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CanyonCarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CanyonCarverConfiguration$$Type = ($CanyonCarverConfiguration);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CanyonCarverConfiguration_ = $CanyonCarverConfiguration$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$WorldCarver" {
import { $ChunkPos$$Type } from "packages/net/minecraft/world/level/$ChunkPos"
import { $CaveCarverConfiguration } from "packages/net/minecraft/world/level/levelgen/carver/$CaveCarverConfiguration"
import { $CarverConfiguration, $CarverConfiguration$$Type } from "packages/net/minecraft/world/level/levelgen/carver/$CarverConfiguration"
import { $ChunkAccess$$Type } from "packages/net/minecraft/world/level/chunk/$ChunkAccess"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $CarvingMask$$Type } from "packages/net/minecraft/world/level/chunk/$CarvingMask"
import { $CanyonCarverConfiguration } from "packages/net/minecraft/world/level/levelgen/carver/$CanyonCarverConfiguration"
import { $Function$$Type } from "packages/java/util/function/$Function"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $Aquifer$$Type } from "packages/net/minecraft/world/level/levelgen/$Aquifer"
import { $Biome } from "packages/net/minecraft/world/level/biome/$Biome"
import { $RandomSource$$Type } from "packages/net/minecraft/util/$RandomSource"
import { $CarvingContext$$Type } from "packages/net/minecraft/world/level/levelgen/carver/$CarvingContext"
import { $ConfiguredWorldCarver } from "packages/net/minecraft/world/level/levelgen/carver/$ConfiguredWorldCarver"
import { $BlockPos$$Type } from "packages/net/minecraft/core/$BlockPos"

export class $WorldCarver<C extends $CarverConfiguration> {
static readonly "CANYON": $WorldCarver<$CanyonCarverConfiguration>
static readonly "CAVE": $WorldCarver<$CaveCarverConfiguration>
static readonly "NETHER_CAVE": $WorldCarver<$CaveCarverConfiguration>

constructor(codec0: $Codec$$Type<C>)

public "carve"(carvingContext0: $CarvingContext$$Type, c1: C, chunkAccess2: $ChunkAccess$$Type, function3: $Function$$Type<$BlockPos$$Type, $Holder<$Biome>>, randomSource4: $RandomSource$$Type, aquifer5: $Aquifer$$Type, chunkPos6: $ChunkPos$$Type, carvingMask7: $CarvingMask$$Type): boolean
public "configured"(c0: C): $ConfiguredWorldCarver<C>
public "configuredCodec"(): $Codec<$ConfiguredWorldCarver<C>>
public "getRange"(): integer
public "isStartChunk"(c0: C, randomSource1: $RandomSource$$Type): boolean
get "range"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenCarver
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenCarverTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldCarver$$Type<C extends $CarverConfiguration> = ($WorldCarver<C> | Special.WorldgenCarver);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldCarver_<C extends $CarverConfiguration> = $WorldCarver$$Type<C>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CanyonCarverConfiguration$CanyonShapeConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CanyonCarverConfiguration$CanyonShapeConfiguration$$Type = ($CanyonCarverConfiguration$CanyonShapeConfiguration);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CanyonCarverConfiguration$CanyonShapeConfiguration_ = $CanyonCarverConfiguration$CanyonShapeConfiguration$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CaveCarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CaveCarverConfiguration$$Type = ($CaveCarverConfiguration);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CaveCarverConfiguration_ = $CaveCarverConfiguration$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$NetherWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NetherWorldCarver$$Type = ($NetherWorldCarver);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NetherWorldCarver_ = $NetherWorldCarver$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CarverDebugSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CarverDebugSettings$$Type = ($CarverDebugSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CarverDebugSettings_ = $CarverDebugSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CaveWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CaveWorldCarver$$Type = ($CaveWorldCarver);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CaveWorldCarver_ = $CaveWorldCarver$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CanyonWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CanyonWorldCarver$$Type = ($CanyonWorldCarver);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CanyonWorldCarver_ = $CanyonWorldCarver$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/carver/$CarvingContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CarvingContext$$Type = ($CarvingContext);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CarvingContext_ = $CarvingContext$$Type;
}
}

