declare module "packages/net/minecraft/world/item/alchemy/$Potion" {
import { $List } from "packages/java/util/$List"
import { $MobEffectInstance, $MobEffectInstance$$Type } from "packages/net/minecraft/world/effect/$MobEffectInstance"
import { $IForgePotion } from "packages/net/minecraftforge/common/extensions/$IForgePotion"
import { $ItemStack$$Type } from "packages/net/minecraft/world/item/$ItemStack"

export class $Potion implements $IForgePotion {
constructor(string0: string, ...mobEffectInstance1s: $MobEffectInstance$$Type[])
constructor(...mobEffectInstance0s: $MobEffectInstance$$Type[])

public static "byName"(string0: string): $Potion
public "getEffects"(): $List<$MobEffectInstance>
public "getName"(string0: string): string
public "hasInstantEffects"(): boolean
public "isFoil"(itemStack0: $ItemStack$$Type): boolean
get "effects"(): $List<$MobEffectInstance>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.Potion
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PotionTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Potion$$Type = ($Potion | Special.Potion);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Potion_ = $Potion$$Type;
}
}

