//priority: 999

const globalModify = [
	"minecraft",
	"trashcans",
	"framedblocks",
	"supplementaries",
	"suppsquared",
	"farmersdelight",
	"chipped",
	"accommodation_",
	"immersive_melodies",
	"comforts",
	"tombstone",
	"toms_storage",
	"potionsmaster",
	"functionalstorage",
	"quark",
	"simpleplanes",
	"sophisticatedbackpacks",
	"waystones",
	"apotheosis",
	"botania",
	"railways",
	"interiors",
	"create_enchantment_industry",
	"immersiveengineering",
	"create",
	"bloodmagic",
	"thermal",
	"biggerreactors",
	"ad_astra",
	"patchouli",
	"hexerei",
	"mna",
	"iceandfire"
];