//priority: 999

function MobCollections() {
	const globalCol = {
		/* TFC */
		tfc_alpaca: "tfc:alpaca",
		tfc_black_bear: "tfc:black_bear",
		tfc_blue_gil: "tfc:bluegill",
		tfc_boar: "tfc:boar",
		tfc_cat: "tfc:cat",
		tfc_chicken: "tfc:chicken",
		tfc_cod: "tfc:cod",
		tfc_cougar: "tfc:cougar",
		tfc_cow: "tfc:cow",
		tfc_crayfish: "tfc:crayfish",
		tfc_deer: "tfc:deer",
		tfc_direwolf: "tfc:direwolf",
		tfc_dog: "tfc:dog",
		tfc_dolphin: "tfc:dolphin",
		tfc_donkey: "tfc:donkey",
		tfc_duck: "tfc:duck",
		tfc_fox: "tfc:fox",
		tfc_goat: "tfc:goat",
		tfc_grizzly_bear: "tfc:grizzly_bear",
		tfc_grouse: "tfc:grouse",
		tfc_horse: "tfc:horse",
		tfc_horseshoe_crab: "tfc:horseshoe_crab",
		tfc_isopod: "tfc:isopod",
		tfc_jellyfish: "tfc:jellyfish",
		tfc_lion: "tfc:lion",
		tfc_lobster: "tfc:lobster",
		tfc_manatee: "tfc:manatee",
		tfc_moose: "tfc:moose",
		tfc_mule: "tfc:mule",
		tfc_musk_ox: "tfc:musk_ox",
		tfc_ocelot: "tfc:ocelot",
		tfc_octopoteuthis: "tfc:octopoteuthis",
		tfc_orca: "tfc:orca",
		tfc_panda: "tfc:panda",
		tfc_panther: "tfc:panther",
		tfc_penguin: "tfc:penguin",
		tfc_pheasant: "tfc:pheasant",
		tfc_pig: "tfc:pig",
		tfc_polar_bear: "tfc:polar_bear",
		tfc_pufferfish: "tfc:pufferfish",
		tfc_quail: "tfc:quail",
		tfc_rabbit: "tfc:rabbit",
		tfc_rat: "tfc:rat",
		tfc_sabertooth: "tfc:sabertooth",
		tfc_salmon: "tfc:salmon",
		tfc_sheep: "tfc:sheep",
		tfc_squid: "tfc:squid",
		tfc_tropical_fish: "tfc:tropical_fish",
		tfc_turkey: "tfc:turkey",
		tfc_turtle: "tfc:turtle",
		tfc_wolf: "tfc:wolf",
		tfc_yak: "tfc:yak",
		/* Beyound */
		beyond_alien: "beyond_earth:alien",
		beyond_alien_zombie: "beyond_earth:alien_zombie",
		beyond_star_crawler: "beyond_earth:star_crawler",
		beyond_pygro: "beyond_earth:pygro",
		beyond_pygro_brute: "beyond_earth:pygro_brute",
		beyond_mogler: "beyond_earth:mogler",
		beyond_martian_raptor: "beyond_earth:martian_raptor",
		/* Thermal Expansion */
		thermal_blitz: "thermal:blitz",
		thermal_blizz: "thermal:blizz",
		thermal_basalz: "thermal:basalz",
		/* Ars Nouveau */
		ars_starbuncle: "ars_nouveau:starbuncle",
		ars_whirlisprig: "ars_nouveau:whirlisprig",
		ars_wilder_hunter: "ars_nouveau:wilden_hunter",
		ars_wilden_guardian: "ars_nouveau:wilden_guardian",
		ars_wilden_stalker: "ars_nouveau:wilden_stalker",
		/* Mana And Artifice */
		mna_spellbreaker: "mna:spellbreaker",
		mna_witch_hunter: "mna:witch_hunter",
		mna_pixie: "mna:pixie",
		mna_mushroom_soldier: "mna:mushroom_soldier",
		mna_demon_imp: "mna:demon_imp",
		mna_lanter_wraith: "mna:lantern_wraith",
		mna_hulking_zombie: "mna:hulking_zombie",
		mna_skeleton_assassin: "mna:skeleton_assassin",
		/* Hexerei */
		hexerei_hex_crow: "hexerei:crow",
		/* Zombie Mobs */
		zombiemobs_zombie_m_cow: "zombiemobs:zombie_cow",
		zombiemobs_zombie_m_pig: "zombiemobs:zombie_pig",
		zombiemobs_zombie_m_llama: "zombiemobs:zombie_llama",
		zombiemobs_zombie_m_goat: "zombiemobs:zombie_goat",
		zombiemobs_zombie_m_fox: "zombiemobs:zombie_fox",
		zombiemobs_zombie_m_wolf: "zombiemobs:zombie_wolf",
		zombiemobs_zombie_m_cat: "zombiemobs:zombie_cat",
		zombiemobs_zombie_m_chicken: "zombiemobs:zombie_chicken",
		zombiemobs_zombie_m_sheep: "zombiemobs:zombie_sheep",
		zombiemobs_zombie_m_bee: "zombiemobs:zombie_bee",
		zombiemobs_zombie_m_ocelot: "zombiemobs:zombie_ocelot",
		zombiemobs_zombie_m_horsee: "zombiemobs:zombie_horsee",
		zombiemobs_zombie_m_donkey: "zombiemobs:zombie_donkey",
		zombiemobs_zombie_m_panda: "zombiemobs:zombie_panda",
		zombiemobs_zombie_m_mule: "zombiemobs:zombie_mule",
		zombiemobs_zombie_m_dolphin: "zombiemobs:zombie_dolphin",
		zombiemobs_zombie_m_turtle: "zombiemobs:zombie_turtle",
		zombiemobs_zombie_m_squid: "zombiemobs:zombie_squid"
	}
}

const MobCol = MobCollections();