declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$VeryBiasedToBottomHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VeryBiasedToBottomHeight$$Type = ($VeryBiasedToBottomHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VeryBiasedToBottomHeight_ = $VeryBiasedToBottomHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$UniformHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $UniformHeight$$Type = ($UniformHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $UniformHeight_ = $UniformHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$HeightProviderType" {
import { $ConstantHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$ConstantHeight"
import { $VeryBiasedToBottomHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$VeryBiasedToBottomHeight"
import { $BiasedToBottomHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$BiasedToBottomHeight"
import { $TrapezoidHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$TrapezoidHeight"
import { $UniformHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$UniformHeight"
import { $HeightProvider, $HeightProvider$$Type } from "packages/net/minecraft/world/level/levelgen/heightproviders/$HeightProvider"
import { $WeightedListHeight } from "packages/net/minecraft/world/level/levelgen/heightproviders/$WeightedListHeight"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"

export interface $HeightProviderType<P extends $HeightProvider> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.HeightProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.HeightProviderTypeTag
}

export namespace $HeightProviderType {
const BIASED_TO_BOTTOM: $HeightProviderType<$BiasedToBottomHeight>
const CONSTANT: $HeightProviderType<$ConstantHeight>
const TRAPEZOID: $HeightProviderType<$TrapezoidHeight>
const UNIFORM: $HeightProviderType<$UniformHeight>
const VERY_BIASED_TO_BOTTOM: $HeightProviderType<$VeryBiasedToBottomHeight>
const WEIGHTED_LIST: $HeightProviderType<$WeightedListHeight>
}
export abstract class $HeightProviderType$$Static<P extends $HeightProvider> implements $HeightProviderType<P> {
static readonly "BIASED_TO_BOTTOM": $HeightProviderType<$BiasedToBottomHeight>
static readonly "CONSTANT": $HeightProviderType<$ConstantHeight>
static readonly "TRAPEZOID": $HeightProviderType<$TrapezoidHeight>
static readonly "UNIFORM": $HeightProviderType<$UniformHeight>
static readonly "VERY_BIASED_TO_BOTTOM": $HeightProviderType<$VeryBiasedToBottomHeight>
static readonly "WEIGHTED_LIST": $HeightProviderType<$WeightedListHeight>

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $HeightProviderType$$Type<P extends $HeightProvider> = ($HeightProviderType<P> | Special.HeightProviderType | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $HeightProviderType_<P extends $HeightProvider> = $HeightProviderType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$WeightedListHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WeightedListHeight$$Type = ($WeightedListHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WeightedListHeight_ = $WeightedListHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$ConstantHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ConstantHeight$$Type = ($ConstantHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ConstantHeight_ = $ConstantHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$TrapezoidHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TrapezoidHeight$$Type = ($TrapezoidHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TrapezoidHeight_ = $TrapezoidHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$BiasedToBottomHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BiasedToBottomHeight$$Type = ($BiasedToBottomHeight);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BiasedToBottomHeight_ = $BiasedToBottomHeight$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/heightproviders/$HeightProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $HeightProvider$$Type = ($HeightProvider);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $HeightProvider_ = $HeightProvider$$Type;
}
}

