declare module "packages/net/minecraft/world/level/levelgen/synth/$BlendedNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlendedNoise$$Type = ($BlendedNoise);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlendedNoise_ = $BlendedNoise$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/synth/$NormalNoise$NoiseParameters" {
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $Record } from "packages/java/lang/$Record"
import { $List$$Type } from "packages/java/util/$List"
import { $DoubleList, $DoubleList$$Type } from "packages/it/unimi/dsi/fastutil/doubles/$DoubleList"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $NormalNoise$NoiseParameters extends $Record {
static readonly "CODEC": $Codec<$Holder<$NormalNoise$NoiseParameters>>
static readonly "DIRECT_CODEC": $Codec<$NormalNoise$NoiseParameters>

constructor(int0: integer, doubleList1: $DoubleList$$Type)
constructor(int0: integer, double1: double, ...double2s: double[])
constructor(int0: integer, list1: $List$$Type<double>)

public "amplitudes"(): $DoubleList
public "firstOctave"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenNoise
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenNoiseTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NormalNoise$NoiseParameters$$Type = ($NormalNoise$NoiseParameters | Special.WorldgenNoise);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NormalNoise$NoiseParameters_ = $NormalNoise$NoiseParameters$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/synth/$NormalNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NormalNoise$$Type = ($NormalNoise);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NormalNoise_ = $NormalNoise$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/synth/$PerlinSimplexNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PerlinSimplexNoise$$Type = ($PerlinSimplexNoise);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PerlinSimplexNoise_ = $PerlinSimplexNoise$$Type;
}
}

