declare module "packages/net/minecraft/stats/$ServerStatsCounter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ServerStatsCounter$$Type = ($ServerStatsCounter);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ServerStatsCounter_ = $ServerStatsCounter$$Type;
}
}

declare module "packages/net/minecraft/stats/$StatType" {
import { $Component } from "packages/net/minecraft/network/chat/$Component"
import { $Consumer$$Type } from "packages/java/util/function/$Consumer"
import { $Stat, $Stat$$Type } from "packages/net/minecraft/stats/$Stat"
import { $StatFormatter$$Type } from "packages/net/minecraft/stats/$StatFormatter"
import { $Registry, $Registry$$Type } from "packages/net/minecraft/core/$Registry"
import { $Iterator } from "packages/java/util/$Iterator"
import { $Spliterator } from "packages/java/util/$Spliterator"
import { $Iterable } from "packages/java/lang/$Iterable"

export class $StatType<T> implements $Iterable<$Stat<T>> {
constructor(registry0: $Registry$$Type<T>)

public "contains"(t0: T): boolean
public "forEach"(consumer0: $Consumer$$Type<$Stat$$Type<T>>): void
public "get"(t0: T): $Stat<T>
public "get"(t0: T, statFormatter1: $StatFormatter$$Type): $Stat<T>
public "getDisplayName"(): $Component
public "getRegistry"(): $Registry<T>
public "getTranslationKey"(): string
public "iterator"(): $Iterator<$Stat<T>>
public "spliterator"(): $Spliterator<$Stat<T>>
[Symbol.iterator](): IterableIterator<$Stat<T>>;
get "displayName"(): $Component
get "registry"(): $Registry<T>
get "translationKey"(): string
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.StatType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.StatTypeTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StatType$$Type<T> = ($StatType<T> | Special.StatType);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StatType_<T> = $StatType$$Type<T>;
}
}

declare module "packages/net/minecraft/stats/$Stat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Stat$$Type<T> = ($Stat<T> | string);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Stat_<T> = $Stat$$Type<T>;
}
}

declare module "packages/net/minecraft/stats/$StatFormatter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StatFormatter$$Type = ($StatFormatter | ((arg0: integer) => string));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StatFormatter_ = $StatFormatter$$Type;
}
}

declare module "packages/net/minecraft/stats/$StatsCounter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StatsCounter$$Type = ($StatsCounter);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StatsCounter_ = $StatsCounter$$Type;
}
}

declare module "packages/net/minecraft/stats/$Stats" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Stats$$Type = ($Stats);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Stats_ = $Stats$$Type;
}
}

declare module "packages/net/minecraft/stats/$ServerRecipeBook" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ServerRecipeBook$$Type = ($ServerRecipeBook);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ServerRecipeBook_ = $ServerRecipeBook$$Type;
}
}

declare module "packages/net/minecraft/stats/$RecipeBook" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RecipeBook$$Type = ($RecipeBook);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RecipeBook_ = $RecipeBook$$Type;
}
}

declare module "packages/net/minecraft/stats/$RecipeBookSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RecipeBookSettings$$Type = ($RecipeBookSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RecipeBookSettings_ = $RecipeBookSettings$$Type;
}
}

