declare module "packages/net/minecraft/world/entity/decoration/$ArmorStand" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArmorStand$$Type = ($ArmorStand);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArmorStand_ = $ArmorStand$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$PaintingVariant" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export class $PaintingVariant {
constructor(int0: integer, int1: integer)

public "getHeight"(): integer
public "getWidth"(): integer
get "height"(): integer
get "width"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.PaintingVariant
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PaintingVariantTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PaintingVariant$$Type = ($PaintingVariant | Special.PaintingVariant);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PaintingVariant_ = $PaintingVariant$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$Painting" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Painting$$Type = ($Painting);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Painting_ = $Painting$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$HangingEntity" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $HangingEntity$$Type = ($HangingEntity);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $HangingEntity_ = $HangingEntity$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$ItemFrame" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ItemFrame$$Type = ($ItemFrame);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ItemFrame_ = $ItemFrame$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$LeashFenceKnotEntity" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LeashFenceKnotEntity$$Type = ($LeashFenceKnotEntity);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LeashFenceKnotEntity_ = $LeashFenceKnotEntity$$Type;
}
}

declare module "packages/net/minecraft/world/entity/decoration/$GlowItemFrame" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GlowItemFrame$$Type = ($GlowItemFrame);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GlowItemFrame_ = $GlowItemFrame$$Type;
}
}

