declare module "packages/net/minecraft/world/item/armortrim/$TrimMaterial" {
import { $Item, $Item$$Type } from "packages/net/minecraft/world/item/$Item"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Component, $Component$$Type } from "packages/net/minecraft/network/chat/$Component"
import { $Record } from "packages/java/lang/$Record"
import { $ArmorMaterials, $ArmorMaterials$$Type } from "packages/net/minecraft/world/item/$ArmorMaterials"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $Map, $Map$$Type } from "packages/java/util/$Map"

export class $TrimMaterial extends $Record {
static readonly "CODEC": $Codec<$Holder<$TrimMaterial>>
static readonly "DIRECT_CODEC": $Codec<$TrimMaterial>

constructor(string0: string, holder1: $Holder$$Type<$Item$$Type>, float2: float, map3: $Map$$Type<$ArmorMaterials$$Type, string>, component4: $Component$$Type)

public "assetName"(): string
public static "create"(string0: string, item1: $Item$$Type, float2: float, component3: $Component$$Type, map4: $Map$$Type<$ArmorMaterials$$Type, string>): $TrimMaterial
public "description"(): $Component
public "ingredient"(): $Holder<$Item>
public "itemModelIndex"(): float
public "overrideArmorMaterials"(): $Map<$ArmorMaterials, string>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.TrimMaterial
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.TrimMaterialTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TrimMaterial$$Type = ($TrimMaterial | Special.TrimMaterial);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TrimMaterial_ = $TrimMaterial$$Type;
}
}

declare module "packages/net/minecraft/world/item/armortrim/$TrimPattern" {
import { $Item, $Item$$Type } from "packages/net/minecraft/world/item/$Item"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Component, $Component$$Type } from "packages/net/minecraft/network/chat/$Component"
import { $Record } from "packages/java/lang/$Record"
import { $TrimMaterial$$Type } from "packages/net/minecraft/world/item/armortrim/$TrimMaterial"
import { $ResourceLocation, $ResourceLocation$$Type } from "packages/net/minecraft/resources/$ResourceLocation"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $TrimPattern extends $Record {
static readonly "CODEC": $Codec<$Holder<$TrimPattern>>
static readonly "DIRECT_CODEC": $Codec<$TrimPattern>

constructor(resourceLocation0: $ResourceLocation$$Type, holder1: $Holder$$Type<$Item$$Type>, component2: $Component$$Type)

public "assetId"(): $ResourceLocation
public "copyWithStyle"(holder0: $Holder$$Type<$TrimMaterial$$Type>): $Component
public "description"(): $Component
public "templateItem"(): $Holder<$Item>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.TrimPattern
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.TrimPatternTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TrimPattern$$Type = ($TrimPattern | Special.TrimPattern);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TrimPattern_ = $TrimPattern$$Type;
}
}

