declare module "packages/net/minecraft/world/level/levelgen/flat/$FlatLayerInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $FlatLayerInfo$$Type = ($FlatLayerInfo);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $FlatLayerInfo_ = $FlatLayerInfo$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/flat/$FlatLevelGeneratorSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $FlatLevelGeneratorSettings$$Type = ($FlatLevelGeneratorSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $FlatLevelGeneratorSettings_ = $FlatLevelGeneratorSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/flat/$FlatLevelGeneratorPreset" {
import { $Item, $Item$$Type } from "packages/net/minecraft/world/item/$Item"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $FlatLevelGeneratorSettings, $FlatLevelGeneratorSettings$$Type } from "packages/net/minecraft/world/level/levelgen/flat/$FlatLevelGeneratorSettings"
import { $Record } from "packages/java/lang/$Record"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $FlatLevelGeneratorPreset extends $Record {
static readonly "CODEC": $Codec<$Holder<$FlatLevelGeneratorPreset>>
static readonly "DIRECT_CODEC": $Codec<$FlatLevelGeneratorPreset>

constructor(holder0: $Holder$$Type<$Item$$Type>, flatLevelGeneratorSettings1: $FlatLevelGeneratorSettings$$Type)

public "displayItem"(): $Holder<$Item>
public "settings"(): $FlatLevelGeneratorSettings
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenFlatLevelGeneratorPreset
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenFlatLevelGeneratorPresetTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $FlatLevelGeneratorPreset$$Type = ($FlatLevelGeneratorPreset | Special.WorldgenFlatLevelGeneratorPreset);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $FlatLevelGeneratorPreset_ = $FlatLevelGeneratorPreset$$Type;
}
}

