declare module "packages/net/minecraft/commands/$SharedSuggestionProvider$ElementSuggestionType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SharedSuggestionProvider$ElementSuggestionType$$Type = ($SharedSuggestionProvider$ElementSuggestionType | ("tags" | "elements" | "all"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SharedSuggestionProvider$ElementSuggestionType_ = $SharedSuggestionProvider$ElementSuggestionType$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$EntityArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EntityArgument$Info$$Type = ($EntityArgument$Info);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EntityArgument$Info_ = $EntityArgument$Info$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandSigningContext" {
import { $PlayerChatMessage$$Type } from "packages/net/minecraft/network/chat/$PlayerChatMessage"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandSigningContext$$Type = ($CommandSigningContext | ((arg0: string) => $PlayerChatMessage$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandSigningContext_ = $CommandSigningContext$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceArgument$Info$$Type<T> = ($ResourceArgument$Info<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceArgument$Info_<T> = $ResourceArgument$Info$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/synchronization/$ArgumentTypeInfo" {
import { $JsonObject$$Type } from "packages/com/google/gson/$JsonObject"
import { $FriendlyByteBuf$$Type } from "packages/net/minecraft/network/$FriendlyByteBuf"
import { $ArgumentType, $ArgumentType$$Type } from "packages/com/mojang/brigadier/arguments/$ArgumentType"
import { $ArgumentTypeInfo$Template, $ArgumentTypeInfo$Template$$Type } from "packages/net/minecraft/commands/synchronization/$ArgumentTypeInfo$Template"

export interface $ArgumentTypeInfo<A extends $ArgumentType<any>, T extends $ArgumentTypeInfo$Template<A>> {
"deserializeFromNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): T
"serializeToJson"(t0: T, jsonObject1: $JsonObject$$Type): void
"serializeToNetwork"(t0: T, friendlyByteBuf1: $FriendlyByteBuf$$Type): void
"unpack"(a0: A): T
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.CommandArgumentType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.CommandArgumentTypeTag
}

export namespace $ArgumentTypeInfo {
const probejs$$marker: never
}
export abstract class $ArgumentTypeInfo$$Static<A extends $ArgumentType<any>, T extends $ArgumentTypeInfo$Template<A>> implements $ArgumentTypeInfo<A, T> {
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArgumentTypeInfo$$Type<A extends $ArgumentType<any>, T extends $ArgumentTypeInfo$Template<A>> = ($ArgumentTypeInfo<A, T> | Special.CommandArgumentType);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArgumentTypeInfo_<A extends $ArgumentType<any>, T extends $ArgumentTypeInfo$Template<A>> = $ArgumentTypeInfo$$Type<A, T>;
}
}

declare module "packages/net/minecraft/commands/arguments/$ScoreHolderArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ScoreHolderArgument$$Type = ($ScoreHolderArgument);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ScoreHolderArgument_ = $ScoreHolderArgument$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceKeyArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceKeyArgument$Info$Template$$Type = ($ResourceKeyArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceKeyArgument$Info$Template_ = $ResourceKeyArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$EntityArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EntityArgument$Info$Template$$Type = ($EntityArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EntityArgument$Info$Template_ = $EntityArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagKeyArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagKeyArgument$Info$$Type<T> = ($ResourceOrTagKeyArgument$Info<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagKeyArgument$Info_<T> = $ResourceOrTagKeyArgument$Info$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/$CommandSourceStack" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandSourceStack$$Type = ($CommandSourceStack);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandSourceStack_ = $CommandSourceStack$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$TimeArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TimeArgument$$Type = ($TimeArgument);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TimeArgument_ = $TimeArgument$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandFunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandFunction$$Type = ($CommandFunction);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandFunction_ = $CommandFunction$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceKeyArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceKeyArgument$$Type<T> = ($ResourceKeyArgument<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceKeyArgument_<T> = $ResourceKeyArgument$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/arguments/selector/$EntitySelector" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EntitySelector$$Type = ($EntitySelector);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EntitySelector_ = $EntitySelector$$Type;
}
}

declare module "packages/net/minecraft/commands/synchronization/$SingletonArgumentInfo" {
import { $ArgumentType, $ArgumentType$$Type } from "packages/com/mojang/brigadier/arguments/$ArgumentType"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SingletonArgumentInfo$$Type<A extends $ArgumentType<any>> = ($SingletonArgumentInfo<A>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SingletonArgumentInfo_<A extends $ArgumentType<any>> = $SingletonArgumentInfo$$Type<A>;
}
}

declare module "packages/net/minecraft/commands/arguments/$TimeArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TimeArgument$Info$$Type = ($TimeArgument$Info);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TimeArgument$Info_ = $TimeArgument$Info$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandFunction$Entry" {
import { $CommandSourceStack } from "packages/net/minecraft/commands/$CommandSourceStack"
import { $Deque } from "packages/java/util/$Deque"
import { $ServerFunctionManager$QueuedCommand } from "packages/net/minecraft/server/$ServerFunctionManager$QueuedCommand"
import { $ServerFunctionManager } from "packages/net/minecraft/server/$ServerFunctionManager"
import { $ServerFunctionManager$TraceCallbacks } from "packages/net/minecraft/server/$ServerFunctionManager$TraceCallbacks"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandFunction$Entry$$Type = ($CommandFunction$Entry | ((arg0: $ServerFunctionManager, arg1: $CommandSourceStack, arg2: $Deque<$ServerFunctionManager$QueuedCommand>, arg3: integer, arg4: integer, arg5: $ServerFunctionManager$TraceCallbacks) => void));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandFunction$Entry_ = $CommandFunction$Entry$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceArgument$Info$Template$$Type = ($ResourceArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceArgument$Info$Template_ = $ResourceArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$TimeArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TimeArgument$Info$Template$$Type = ($TimeArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TimeArgument$Info$Template_ = $TimeArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ArgumentSignatures$Entry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArgumentSignatures$Entry$$Type = ($ArgumentSignatures$Entry);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArgumentSignatures$Entry_ = $ArgumentSignatures$Entry$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$EntityAnchorArgument$Anchor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EntityAnchorArgument$Anchor$$Type = ($EntityAnchorArgument$Anchor | ("feet" | "eyes"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EntityAnchorArgument$Anchor_ = $EntityAnchorArgument$Anchor$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagKeyArgument$Result" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagKeyArgument$Result$$Type<T> = ($ResourceOrTagKeyArgument$Result<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagKeyArgument$Result_<T> = $ResourceOrTagKeyArgument$Result$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/arguments/$ScoreHolderArgument$Result" {
import { $CommandSourceStack } from "packages/net/minecraft/commands/$CommandSourceStack"
import { $Collection, $Collection$$Type } from "packages/java/util/$Collection"
import { $Supplier } from "packages/java/util/function/$Supplier"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ScoreHolderArgument$Result$$Type = ($ScoreHolderArgument$Result | ((arg0: $CommandSourceStack, arg1: $Supplier<$Collection<string>>) => $Collection$$Type<string>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ScoreHolderArgument$Result_ = $ScoreHolderArgument$Result$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$EntityArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EntityArgument$$Type = ($EntityArgument);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EntityArgument_ = $EntityArgument$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagArgument$$Type<T> = ($ResourceOrTagArgument<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagArgument_<T> = $ResourceOrTagArgument$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/synchronization/$ArgumentTypeInfo$Template" {
import { $ArgumentType, $ArgumentType$$Type } from "packages/com/mojang/brigadier/arguments/$ArgumentType"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArgumentTypeInfo$Template$$Type<A extends $ArgumentType<any>> = ($ArgumentTypeInfo$Template<A>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArgumentTypeInfo$Template_<A extends $ArgumentType<any>> = $ArgumentTypeInfo$Template$$Type<A>;
}
}

declare module "packages/net/minecraft/commands/$SharedSuggestionProvider$TextCoordinates" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SharedSuggestionProvider$TextCoordinates$$Type = ($SharedSuggestionProvider$TextCoordinates);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SharedSuggestionProvider$TextCoordinates_ = $SharedSuggestionProvider$TextCoordinates$$Type;
}
}

declare module "packages/net/minecraft/commands/$Commands$CommandSelection" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Commands$CommandSelection$$Type = ($Commands$CommandSelection | ("all" | "dedicated" | "integrated"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Commands$CommandSelection_ = $Commands$CommandSelection$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagKeyArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagKeyArgument$Info$Template$$Type = ($ResourceOrTagKeyArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagKeyArgument$Info$Template_ = $ResourceOrTagKeyArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandBuildContext$MissingTagAccessPolicy" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandBuildContext$MissingTagAccessPolicy$$Type = ($CommandBuildContext$MissingTagAccessPolicy | ("create_new" | "fail"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandBuildContext$MissingTagAccessPolicy_ = $CommandBuildContext$MissingTagAccessPolicy$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandBuildContext" {
import { $Registry } from "packages/net/minecraft/core/$Registry"
import { $HolderLookup$$Type } from "packages/net/minecraft/core/$HolderLookup"
import { $ResourceKey } from "packages/net/minecraft/resources/$ResourceKey"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandBuildContext$$Type = ($CommandBuildContext | ((arg0: $ResourceKey<$Registry<T>>) => $HolderLookup$$Type<T>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandBuildContext_ = $CommandBuildContext$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandSource$$Type = ($CommandSource);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandSource_ = $CommandSource$$Type;
}
}

declare module "packages/net/minecraft/commands/$Commands" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Commands$$Type = ($Commands);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Commands_ = $Commands$$Type;
}
}

declare module "packages/net/minecraft/commands/$Commands$ParseFunction" {
import { $StringReader } from "packages/com/mojang/brigadier/$StringReader"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Commands$ParseFunction$$Type = ($Commands$ParseFunction | ((arg0: $StringReader) => void));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Commands$ParseFunction_ = $Commands$ParseFunction$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ArgumentSignatures" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArgumentSignatures$$Type = ($ArgumentSignatures);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArgumentSignatures_ = $ArgumentSignatures$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagArgument$Info$Template$$Type = ($ResourceOrTagArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagArgument$Info$Template_ = $ResourceOrTagArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ScoreHolderArgument$Info$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ScoreHolderArgument$Info$Template$$Type = ($ScoreHolderArgument$Info$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ScoreHolderArgument$Info$Template_ = $ScoreHolderArgument$Info$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/synchronization/$SingletonArgumentInfo$Template" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SingletonArgumentInfo$Template$$Type = ($SingletonArgumentInfo$Template);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SingletonArgumentInfo$Template_ = $SingletonArgumentInfo$Template$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagKeyArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagKeyArgument$$Type<T> = ($ResourceOrTagKeyArgument<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagKeyArgument_<T> = $ResourceOrTagKeyArgument$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/$SharedSuggestionProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SharedSuggestionProvider$$Type = ($SharedSuggestionProvider);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SharedSuggestionProvider_ = $SharedSuggestionProvider$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagArgument$Info$$Type<T> = ($ResourceOrTagArgument$Info<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagArgument$Info_<T> = $ResourceOrTagArgument$Info$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceKeyArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceKeyArgument$Info$$Type<T> = ($ResourceKeyArgument$Info<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceKeyArgument$Info_<T> = $ResourceKeyArgument$Info$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceArgument" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceArgument$$Type<T> = ($ResourceArgument<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceArgument_<T> = $ResourceArgument$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/$CommandFunction$CacheableFunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandFunction$CacheableFunction$$Type = ($CommandFunction$CacheableFunction);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandFunction$CacheableFunction_ = $CommandFunction$CacheableFunction$$Type;
}
}

declare module "packages/net/minecraft/commands/$CommandBuildContext$Configurable" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CommandBuildContext$Configurable$$Type = ($CommandBuildContext$Configurable);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CommandBuildContext$Configurable_ = $CommandBuildContext$Configurable$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ResourceOrTagArgument$Result" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ResourceOrTagArgument$Result$$Type<T> = ($ResourceOrTagArgument$Result<T>);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ResourceOrTagArgument$Result_<T> = $ResourceOrTagArgument$Result$$Type<T>;
}
}

declare module "packages/net/minecraft/commands/arguments/$ScoreHolderArgument$Info" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ScoreHolderArgument$Info$$Type = ($ScoreHolderArgument$Info);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ScoreHolderArgument$Info_ = $ScoreHolderArgument$Info$$Type;
}
}

declare module "packages/net/minecraft/commands/arguments/$ArgumentSignatures$Signer" {
import { $MessageSignature$$Type } from "packages/net/minecraft/network/chat/$MessageSignature"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ArgumentSignatures$Signer$$Type = ($ArgumentSignatures$Signer | ((arg0: string) => $MessageSignature$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ArgumentSignatures$Signer_ = $ArgumentSignatures$Signer$$Type;
}
}

