declare module "packages/net/minecraft/world/effect/$MobEffectInstance$FactorData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MobEffectInstance$FactorData$$Type = ($MobEffectInstance$FactorData);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MobEffectInstance$FactorData_ = $MobEffectInstance$FactorData$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$MobEffect" {
import { $Component } from "packages/net/minecraft/network/chat/$Component"
import { $MobEffectInstance$$Type } from "packages/net/minecraft/world/effect/$MobEffectInstance"
import { $ItemStack } from "packages/net/minecraft/world/item/$ItemStack"
import { $LivingEntity$$Type } from "packages/net/minecraft/world/entity/$LivingEntity"
import { $MobEffectInstance$FactorData } from "packages/net/minecraft/world/effect/$MobEffectInstance$FactorData"
import { $AttributeMap$$Type } from "packages/net/minecraft/world/entity/ai/attributes/$AttributeMap"
import { $IClientMobEffectExtensions$$Type } from "packages/net/minecraftforge/client/extensions/common/$IClientMobEffectExtensions"
import { $Consumer$$Type } from "packages/java/util/function/$Consumer"
import { $IForgeMobEffect } from "packages/net/minecraftforge/common/extensions/$IForgeMobEffect"
import { $Attribute, $Attribute$$Type } from "packages/net/minecraft/world/entity/ai/attributes/$Attribute"
import { $AttributeModifier$Operation$$Type } from "packages/net/minecraft/world/entity/ai/attributes/$AttributeModifier$Operation"
import { $List } from "packages/java/util/$List"
import { $Optional } from "packages/java/util/$Optional"
import { $AttributeModifier, $AttributeModifier$$Type } from "packages/net/minecraft/world/entity/ai/attributes/$AttributeModifier"
import { $Supplier$$Type } from "packages/java/util/function/$Supplier"
import { $MobEffectCategory } from "packages/net/minecraft/world/effect/$MobEffectCategory"
import { $Entity$$Type } from "packages/net/minecraft/world/entity/$Entity"
import { $Map } from "packages/java/util/$Map"

export class $MobEffect implements $IForgeMobEffect {
public "addAttributeModifier"(attribute0: $Attribute$$Type, string1: string, double2: double, operation3: $AttributeModifier$Operation$$Type): $MobEffect
public "addAttributeModifiers"(livingEntity0: $LivingEntity$$Type, attributeMap1: $AttributeMap$$Type, int2: integer): void
public "applyEffectTick"(livingEntity0: $LivingEntity$$Type, int1: integer): void
public "applyInstantenousEffect"(entity0: $Entity$$Type, entity1: $Entity$$Type, livingEntity2: $LivingEntity$$Type, int3: integer, double4: double): void
public static "byId"(int0: integer): $MobEffect
public "createFactorData"(): $Optional<$MobEffectInstance$FactorData>
public "getAttributeModifierValue"(int0: integer, attributeModifier1: $AttributeModifier$$Type): double
public "getAttributeModifiers"(): $Map<$Attribute, $AttributeModifier>
public "getCategory"(): $MobEffectCategory
public "getColor"(): integer
public "getCurativeItems"(): $List<$ItemStack>
public "getDescriptionId"(): string
public "getDisplayName"(): $Component
public "getEffectRendererInternal"(): any
public static "getId"(mobEffect0: $MobEffect$$Type): integer
public static "getIdFromNullable"(mobEffect0: $MobEffect$$Type): integer
public "getSortOrder"(mobEffectInstance0: $MobEffectInstance$$Type): integer
public "initializeClient"(consumer0: $Consumer$$Type<$IClientMobEffectExtensions$$Type>): void
public "isBeneficial"(): boolean
public "isDurationEffectTick"(int0: integer, int1: integer): boolean
public "isInstantenous"(): boolean
public "removeAttributeModifiers"(livingEntity0: $LivingEntity$$Type, attributeMap1: $AttributeMap$$Type, int2: integer): void
public "setFactorDataFactory"(supplier0: $Supplier$$Type<$MobEffectInstance$FactorData>): $MobEffect
get "attributeModifiers"(): $Map<$Attribute, $AttributeModifier>
get "category"(): $MobEffectCategory
get "color"(): integer
get "curativeItems"(): $List<$ItemStack>
get "descriptionId"(): string
get "displayName"(): $Component
get "effectRendererInternal"(): any
get "beneficial"(): boolean
get "instantenous"(): boolean
set "factorDataFactory"(value: $Supplier$$Type<$MobEffectInstance$FactorData>)
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.MobEffect
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.MobEffectTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MobEffect$$Type = ($MobEffect | Special.MobEffect);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MobEffect_ = $MobEffect$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$MobEffectInstance" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MobEffectInstance$$Type = ($MobEffectInstance);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MobEffectInstance_ = $MobEffectInstance$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$AbsoptionMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AbsoptionMobEffect$$Type = ($AbsoptionMobEffect);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AbsoptionMobEffect_ = $AbsoptionMobEffect$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$HealthBoostMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $HealthBoostMobEffect$$Type = ($HealthBoostMobEffect);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $HealthBoostMobEffect_ = $HealthBoostMobEffect$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$InstantenousMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $InstantenousMobEffect$$Type = ($InstantenousMobEffect);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $InstantenousMobEffect_ = $InstantenousMobEffect$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$AttackDamageMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AttackDamageMobEffect$$Type = ($AttackDamageMobEffect);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AttackDamageMobEffect_ = $AttackDamageMobEffect$$Type;
}
}

declare module "packages/net/minecraft/world/effect/$MobEffectCategory" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MobEffectCategory$$Type = ($MobEffectCategory | ("beneficial" | "harmful" | "neutral"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MobEffectCategory_ = $MobEffectCategory$$Type;
}
}

