declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction$Visitor" {
import { $DensityFunction, $DensityFunction$$Type } from "packages/net/minecraft/world/level/levelgen/$DensityFunction"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$Visitor$$Type = ($DensityFunction$Visitor | ((arg0: $DensityFunction) => $DensityFunction$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction$Visitor_ = $DensityFunction$Visitor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction$FunctionContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$FunctionContext$$Type = ($DensityFunction$FunctionContext);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction$FunctionContext_ = $DensityFunction$FunctionContext$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$SurfaceRules$RuleSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SurfaceRules$RuleSource$$Type = ($SurfaceRules$RuleSource);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SurfaceRules$RuleSource_ = $SurfaceRules$RuleSource$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction" {
import { $DensityFunction$Visitor$$Type } from "packages/net/minecraft/world/level/levelgen/$DensityFunction$Visitor"
import { $DensityFunction$ContextProvider$$Type } from "packages/net/minecraft/world/level/levelgen/$DensityFunction$ContextProvider"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $KeyDispatchDataCodec } from "packages/net/minecraft/util/$KeyDispatchDataCodec"
import { $DensityFunction$FunctionContext$$Type } from "packages/net/minecraft/world/level/levelgen/$DensityFunction$FunctionContext"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export interface $DensityFunction {
"abs"(): $DensityFunction
"clamp"(double0: double, double1: double): $DensityFunction
"codec"(): $KeyDispatchDataCodec<$DensityFunction>
"compute"(functionContext0: $DensityFunction$FunctionContext$$Type): double
"cube"(): $DensityFunction
"fillArray"(double0s: double[], contextProvider1: $DensityFunction$ContextProvider$$Type): void
"halfNegative"(): $DensityFunction
"mapAll"(visitor0: $DensityFunction$Visitor$$Type): $DensityFunction
"maxValue"(): double
"minValue"(): double
"quarterNegative"(): $DensityFunction
"square"(): $DensityFunction
"squeeze"(): $DensityFunction
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenDensityFunction
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenDensityFunctionTag
}

export namespace $DensityFunction {
const CODEC: $Codec<$Holder<$DensityFunction>>
const DIRECT_CODEC: $Codec<$DensityFunction>
const HOLDER_HELPER_CODEC: $Codec<$DensityFunction>
}
export abstract class $DensityFunction$$Static implements $DensityFunction {
static readonly "CODEC": $Codec<$Holder<$DensityFunction>>
static readonly "DIRECT_CODEC": $Codec<$DensityFunction>
static readonly "HOLDER_HELPER_CODEC": $Codec<$DensityFunction>

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$$Type = ($DensityFunction | Special.WorldgenDensityFunction);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction_ = $DensityFunction$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$YClampedGradient" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$YClampedGradient$$Type = ($DensityFunctions$YClampedGradient);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$YClampedGradient_ = $DensityFunctions$YClampedGradient$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$TwoArgumentSimpleFunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$TwoArgumentSimpleFunction$$Type = ($DensityFunctions$TwoArgumentSimpleFunction);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$TwoArgumentSimpleFunction_ = $DensityFunctions$TwoArgumentSimpleFunction$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$GeodeBlockSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GeodeBlockSettings$$Type = ($GeodeBlockSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GeodeBlockSettings_ = $GeodeBlockSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$Aquifer$FluidPicker" {
import { $Aquifer$FluidStatus$$Type } from "packages/net/minecraft/world/level/levelgen/$Aquifer$FluidStatus"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Aquifer$FluidPicker$$Type = ($Aquifer$FluidPicker | ((arg0: integer, arg1: integer, arg2: integer) => $Aquifer$FluidStatus$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Aquifer$FluidPicker_ = $Aquifer$FluidPicker$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$TwoArgumentSimpleFunction$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$TwoArgumentSimpleFunction$Type$$Type = ($DensityFunctions$TwoArgumentSimpleFunction$Type | ("add" | "mul" | "min" | "max"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$TwoArgumentSimpleFunction$Type_ = $DensityFunctions$TwoArgumentSimpleFunction$Type$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$MarkerOrMarked" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$MarkerOrMarked$$Type = ($DensityFunctions$MarkerOrMarked);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$MarkerOrMarked_ = $DensityFunctions$MarkerOrMarked$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$Ap2" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$Ap2$$Type = ($DensityFunctions$Ap2);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$Ap2_ = $DensityFunctions$Ap2$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$Heightmap$Types" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Heightmap$Types$$Type = ($Heightmap$Types | ("world_surface_wg" | "world_surface" | "ocean_floor_wg" | "ocean_floor" | "motion_blocking" | "motion_blocking_no_leaves"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Heightmap$Types_ = $Heightmap$Types$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$LegacyRandomSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LegacyRandomSource$$Type = ($LegacyRandomSource);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LegacyRandomSource_ = $LegacyRandomSource$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$Clamp" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$Clamp$$Type = ($DensityFunctions$Clamp);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$Clamp_ = $DensityFunctions$Clamp$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$GeodeLayerSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GeodeLayerSettings$$Type = ($GeodeLayerSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GeodeLayerSettings_ = $GeodeLayerSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$GeodeCrackSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GeodeCrackSettings$$Type = ($GeodeCrackSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GeodeCrackSettings_ = $GeodeCrackSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$NoiseRouter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NoiseRouter$$Type = ($NoiseRouter);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NoiseRouter_ = $NoiseRouter$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$NoiseGeneratorSettings" {
import { $BlockState, $BlockState$$Type } from "packages/net/minecraft/world/level/block/state/$BlockState"
import { $WorldgenRandom$Algorithm } from "packages/net/minecraft/world/level/levelgen/$WorldgenRandom$Algorithm"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $BootstapContext$$Type } from "packages/net/minecraft/data/worldgen/$BootstapContext"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $Record } from "packages/java/lang/$Record"
import { $SurfaceRules$RuleSource, $SurfaceRules$RuleSource$$Type } from "packages/net/minecraft/world/level/levelgen/$SurfaceRules$RuleSource"
import { $NoiseGeneratorSettingsAccessor } from "packages/com/github/alexthe666/citadel/server/generation/$NoiseGeneratorSettingsAccessor"
import { $List, $List$$Type } from "packages/java/util/$List"
import { $NoiseRouter, $NoiseRouter$$Type } from "packages/net/minecraft/world/level/levelgen/$NoiseRouter"
import { $NoiseSettings, $NoiseSettings$$Type } from "packages/net/minecraft/world/level/levelgen/$NoiseSettings"
import { $Climate$ParameterPoint, $Climate$ParameterPoint$$Type } from "packages/net/minecraft/world/level/biome/$Climate$ParameterPoint"
import { $ResourceKey } from "packages/net/minecraft/resources/$ResourceKey"

export class $NoiseGeneratorSettings extends $Record implements $NoiseGeneratorSettingsAccessor {
static readonly "AMPLIFIED": $ResourceKey<$NoiseGeneratorSettings>
static readonly "CAVES": $ResourceKey<$NoiseGeneratorSettings>
static readonly "CODEC": $Codec<$Holder<$NoiseGeneratorSettings>>
static readonly "DIRECT_CODEC": $Codec<$NoiseGeneratorSettings>
static readonly "END": $ResourceKey<$NoiseGeneratorSettings>
static readonly "FLOATING_ISLANDS": $ResourceKey<$NoiseGeneratorSettings>
static readonly "LARGE_BIOMES": $ResourceKey<$NoiseGeneratorSettings>
static readonly "NETHER": $ResourceKey<$NoiseGeneratorSettings>
static readonly "OVERWORLD": $ResourceKey<$NoiseGeneratorSettings>

constructor(noiseSettings0: $NoiseSettings$$Type, blockState1: $BlockState$$Type, blockState2: $BlockState$$Type, noiseRouter3: $NoiseRouter$$Type, ruleSource4: $SurfaceRules$RuleSource$$Type, list5: $List$$Type<$Climate$ParameterPoint$$Type>, int6: integer, boolean7: boolean, boolean8: boolean, boolean9: boolean, boolean10: boolean)

public "aquifersEnabled"(): boolean
public static "bootstrap"(bootstapContext0: $BootstapContext$$Type<$NoiseGeneratorSettings$$Type>): void
public static "caves"(bootstapContext0: $BootstapContext$$Type<any>): $NoiseGeneratorSettings
public "defaultBlock"(): $BlockState
public "defaultFluid"(): $BlockState
/** @deprecated */
public "disableMobGeneration"(): boolean
public static "dummy"(): $NoiseGeneratorSettings
public static "end"(bootstapContext0: $BootstapContext$$Type<any>): $NoiseGeneratorSettings
public static "floatingIslands"(bootstapContext0: $BootstapContext$$Type<any>): $NoiseGeneratorSettings
public "getRandomSource"(): $WorldgenRandom$Algorithm
public "isAquifersEnabled"(): boolean
public static "nether"(bootstapContext0: $BootstapContext$$Type<any>): $NoiseGeneratorSettings
public "noiseRouter"(): $NoiseRouter
public "noiseSettings"(): $NoiseSettings
public "onSaveData"(boolean0: boolean): void
public "oreVeinsEnabled"(): boolean
public static "overworld"(bootstapContext0: $BootstapContext$$Type<any>, boolean1: boolean, boolean2: boolean): $NoiseGeneratorSettings
public "seaLevel"(): integer
public "spawnTarget"(): $List<$Climate$ParameterPoint>
public "surfaceRule"(): $SurfaceRules$RuleSource
public "useLegacyRandomSource"(): boolean
get "randomSource"(): $WorldgenRandom$Algorithm
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenNoiseSettings
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenNoiseSettingsTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NoiseGeneratorSettings$$Type = ($NoiseGeneratorSettings | Special.WorldgenNoiseSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NoiseGeneratorSettings_ = $NoiseGeneratorSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$NoiseChunk" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NoiseChunk$$Type = ($NoiseChunk);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NoiseChunk_ = $NoiseChunk$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$NoiseBasedChunkGenerator" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NoiseBasedChunkGenerator$$Type = ($NoiseBasedChunkGenerator);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NoiseBasedChunkGenerator_ = $NoiseBasedChunkGenerator$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldGenerationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldGenerationContext$$Type = ($WorldGenerationContext);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldGenerationContext_ = $WorldGenerationContext$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$RandomState" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RandomState$$Type = ($RandomState);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RandomState_ = $RandomState$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$SurfaceRules$SurfaceRule" {
import { $BlockState$$Type } from "packages/net/minecraft/world/level/block/state/$BlockState"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SurfaceRules$SurfaceRule$$Type = ($SurfaceRules$SurfaceRule | ((arg0: integer, arg1: integer, arg2: integer) => $BlockState$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SurfaceRules$SurfaceRule_ = $SurfaceRules$SurfaceRule$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldDimensions" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldDimensions$$Type = ($WorldDimensions);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldDimensions_ = $WorldDimensions$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$BitRandomSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BitRandomSource$$Type = ($BitRandomSource);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BitRandomSource_ = $BitRandomSource$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$GenerationStep$Carving" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GenerationStep$Carving$$Type = ($GenerationStep$Carving | ("air" | "liquid"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GenerationStep$Carving_ = $GenerationStep$Carving$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$Marker" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$Marker$$Type = ($DensityFunctions$Marker);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$Marker_ = $DensityFunctions$Marker$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldgenRandom$Algorithm" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldgenRandom$Algorithm$$Type = ($WorldgenRandom$Algorithm | ("legacy" | "xoroshiro"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldgenRandom$Algorithm_ = $WorldgenRandom$Algorithm$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$SurfaceSystem" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SurfaceSystem$$Type = ($SurfaceSystem);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SurfaceSystem_ = $SurfaceSystem$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction$SimpleFunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$SimpleFunction$$Type = ($DensityFunction$SimpleFunction);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction$SimpleFunction_ = $DensityFunction$SimpleFunction$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction$ContextProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$ContextProvider$$Type = ($DensityFunction$ContextProvider);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction$ContextProvider_ = $DensityFunction$ContextProvider$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$Aquifer$FluidStatus" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Aquifer$FluidStatus$$Type = ($Aquifer$FluidStatus);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Aquifer$FluidStatus_ = $Aquifer$FluidStatus$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldgenRandom" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldgenRandom$$Type = ($WorldgenRandom);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldgenRandom_ = $WorldgenRandom$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$Constant" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$Constant$$Type = ($DensityFunctions$Constant);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$Constant_ = $DensityFunctions$Constant$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldOptions" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldOptions$$Type = ($WorldOptions);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldOptions_ = $WorldOptions$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$Heightmap" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Heightmap$$Type = ($Heightmap);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Heightmap_ = $Heightmap$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$BelowZeroRetrogen" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BelowZeroRetrogen$$Type = ($BelowZeroRetrogen);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BelowZeroRetrogen_ = $BelowZeroRetrogen$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$PositionalRandomFactory" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PositionalRandomFactory$$Type = ($PositionalRandomFactory);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PositionalRandomFactory_ = $PositionalRandomFactory$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$SurfaceRules$Context" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SurfaceRules$Context$$Type = ($SurfaceRules$Context);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SurfaceRules$Context_ = $SurfaceRules$Context$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldGenSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldGenSettings$$Type = ($WorldGenSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldGenSettings_ = $WorldGenSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$WorldDimensions$Complete" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldDimensions$Complete$$Type = ($WorldDimensions$Complete);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldDimensions$Complete_ = $WorldDimensions$Complete$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$BeardifierOrMarker" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$BeardifierOrMarker$$Type = ($DensityFunctions$BeardifierOrMarker);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$BeardifierOrMarker_ = $DensityFunctions$BeardifierOrMarker$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$Marker$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$Marker$Type$$Type = ($DensityFunctions$Marker$Type | ("interpolated" | "flatcache" | "cache2d" | "cacheonce" | "cacheallincell"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$Marker$Type_ = $DensityFunctions$Marker$Type$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$NoiseSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NoiseSettings$$Type = ($NoiseSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NoiseSettings_ = $NoiseSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$PureTransformer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$PureTransformer$$Type = ($DensityFunctions$PureTransformer);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$PureTransformer_ = $DensityFunctions$PureTransformer$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$GenerationStep$Decoration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GenerationStep$Decoration$$Type = ($GenerationStep$Decoration | ("raw_generation" | "lakes" | "local_modifications" | "underground_structures" | "surface_structures" | "strongholds" | "underground_ores" | "underground_decoration" | "fluid_springs" | "vegetal_decoration" | "top_layer_modification"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GenerationStep$Decoration_ = $GenerationStep$Decoration$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunctions$RangeChoice" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunctions$RangeChoice$$Type = ($DensityFunctions$RangeChoice);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunctions$RangeChoice_ = $DensityFunctions$RangeChoice$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$DensityFunction$NoiseHolder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DensityFunction$NoiseHolder$$Type = ($DensityFunction$NoiseHolder);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DensityFunction$NoiseHolder_ = $DensityFunction$NoiseHolder$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$Aquifer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Aquifer$$Type = ($Aquifer);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Aquifer_ = $Aquifer$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/$VerticalAnchor" {
import { $WorldGenerationContext } from "packages/net/minecraft/world/level/levelgen/$WorldGenerationContext"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $VerticalAnchor$$Type = ($VerticalAnchor | ((arg0: $WorldGenerationContext) => integer));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $VerticalAnchor_ = $VerticalAnchor$$Type;
}
}

