declare module "packages/net/minecraft/world/level/levelgen/presets/$WorldPreset" {
import { $WorldDimensions } from "packages/net/minecraft/world/level/levelgen/$WorldDimensions"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $LevelStem, $LevelStem$$Type } from "packages/net/minecraft/world/level/dimension/$LevelStem"
import { $Optional } from "packages/java/util/$Optional"
import { $ResourceKey$$Type } from "packages/net/minecraft/resources/$ResourceKey"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $Map$$Type } from "packages/java/util/$Map"

export class $WorldPreset {
static readonly "CODEC": $Codec<$Holder<$WorldPreset>>
static readonly "DIRECT_CODEC": $Codec<$WorldPreset>

constructor(map0: $Map$$Type<$ResourceKey$$Type<$LevelStem$$Type>, $LevelStem$$Type>)

public "createWorldDimensions"(): $WorldDimensions
public "overworld"(): $Optional<$LevelStem>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenWorldPreset
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenWorldPresetTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WorldPreset$$Type = ($WorldPreset | Special.WorldgenWorldPreset);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WorldPreset_ = $WorldPreset$$Type;
}
}

