declare module "packages/net/minecraft/world/level/levelgen/structure/$Structure$GenerationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Structure$GenerationContext$$Type = ($Structure$GenerationContext);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Structure$GenerationContext_ = $Structure$GenerationContext$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RuleTestType" {
import { $BlockMatchTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockMatchTest"
import { $RandomBlockMatchTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RandomBlockMatchTest"
import { $AlwaysTrueTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$AlwaysTrueTest"
import { $BlockStateMatchTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockStateMatchTest"
import { $RandomBlockStateMatchTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RandomBlockStateMatchTest"
import { $RuleTest, $RuleTest$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RuleTest"
import { $TagMatchTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$TagMatchTest"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"

export interface $RuleTestType<P extends $RuleTest> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.RuleTest
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.RuleTestTag
}

export namespace $RuleTestType {
const ALWAYS_TRUE_TEST: $RuleTestType<$AlwaysTrueTest>
const BLOCKSTATE_TEST: $RuleTestType<$BlockStateMatchTest>
const BLOCK_TEST: $RuleTestType<$BlockMatchTest>
const RANDOM_BLOCKSTATE_TEST: $RuleTestType<$RandomBlockStateMatchTest>
const RANDOM_BLOCK_TEST: $RuleTestType<$RandomBlockMatchTest>
const TAG_TEST: $RuleTestType<$TagMatchTest>
function register<P extends $RuleTest>(string0: string, codec1: $Codec$$Type<P>): $RuleTestType<P>
}
export abstract class $RuleTestType$$Static<P extends $RuleTest> implements $RuleTestType<P> {
static readonly "ALWAYS_TRUE_TEST": $RuleTestType<$AlwaysTrueTest>
static readonly "BLOCKSTATE_TEST": $RuleTestType<$BlockStateMatchTest>
static readonly "BLOCK_TEST": $RuleTestType<$BlockMatchTest>
static readonly "RANDOM_BLOCKSTATE_TEST": $RuleTestType<$RandomBlockStateMatchTest>
static readonly "RANDOM_BLOCK_TEST": $RuleTestType<$RandomBlockMatchTest>
static readonly "TAG_TEST": $RuleTestType<$TagMatchTest>

static "register"<P extends $RuleTest>(string0: string, codec1: $Codec$$Type<P>): $RuleTestType<P>
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuleTestType$$Type<P extends $RuleTest> = ($RuleTestType<P> | Special.RuleTest | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuleTestType_<P extends $RuleTest> = $RuleTestType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$WoodlandMansionStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $WoodlandMansionStructure$$Type = ($WoodlandMansionStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $WoodlandMansionStructure_ = $WoodlandMansionStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$TagMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TagMatchTest$$Type = ($TagMatchTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TagMatchTest_ = $TagMatchTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplate$StructureBlockInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplate$StructureBlockInfo$$Type = ($StructureTemplate$StructureBlockInfo);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplate$StructureBlockInfo_ = $StructureTemplate$StructureBlockInfo$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$RandomSpreadStructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RandomSpreadStructurePlacement$$Type = ($RandomSpreadStructurePlacement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RandomSpreadStructurePlacement_ = $RandomSpreadStructurePlacement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$CappedProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CappedProcessor$$Type = ($CappedProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CappedProcessor_ = $CappedProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureSet" {
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Record } from "packages/java/lang/$Record"
import { $Structure$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$Structure"
import { $List, $List$$Type } from "packages/java/util/$List"
import { $StructurePlacement, $StructurePlacement$$Type } from "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacement"
import { $StructureSet$StructureSelectionEntry, $StructureSet$StructureSelectionEntry$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$StructureSet$StructureSelectionEntry"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $StructureSet extends $Record {
static readonly "CODEC": $Codec<$Holder<$StructureSet>>
static readonly "DIRECT_CODEC": $Codec<$StructureSet>

constructor(holder0: $Holder$$Type<$Structure$$Type>, structurePlacement1: $StructurePlacement$$Type)
constructor(list0: $List$$Type<$StructureSet$StructureSelectionEntry$$Type>, structurePlacement1: $StructurePlacement$$Type)

public static "entry"(holder0: $Holder$$Type<$Structure$$Type>, int1: integer): $StructureSet$StructureSelectionEntry
public static "entry"(holder0: $Holder$$Type<$Structure$$Type>): $StructureSet$StructureSelectionEntry
public "placement"(): $StructurePlacement
public "structures"(): $List<$StructureSet$StructureSelectionEntry>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureSet
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureSetTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureSet$$Type = ($StructureSet | Special.WorldgenStructureSet);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureSet_ = $StructureSet$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$NetherFossilStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NetherFossilStructure$$Type = ($NetherFossilStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NetherFossilStructure_ = $NetherFossilStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$AlwaysTrueTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AlwaysTrueTest$$Type = ($AlwaysTrueTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AlwaysTrueTest_ = $AlwaysTrueTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockAgeProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlockAgeProcessor$$Type = ($BlockAgeProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlockAgeProcessor_ = $BlockAgeProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplateManager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplateManager$$Type = ($StructureTemplateManager);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplateManager_ = $StructureTemplateManager$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$ProcessorRule" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ProcessorRule$$Type = ($ProcessorRule);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ProcessorRule_ = $ProcessorRule$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$EndCityStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EndCityStructure$$Type = ($EndCityStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EndCityStructure_ = $EndCityStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$OceanMonumentStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $OceanMonumentStructure$$Type = ($OceanMonumentStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $OceanMonumentStructure_ = $OceanMonumentStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockIgnoreProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlockIgnoreProcessor$$Type = ($BlockIgnoreProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlockIgnoreProcessor_ = $BlockIgnoreProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$StructureTemplatePool$Projection" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplatePool$Projection$$Type = ($StructureTemplatePool$Projection | ("terrain_matching" | "rigid"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplatePool$Projection_ = $StructureTemplatePool$Projection$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePlacement$$Type = ($StructurePlacement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePlacement_ = $StructurePlacement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureSpawnOverride$BoundingBoxType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureSpawnOverride$BoundingBoxType$$Type = ($StructureSpawnOverride$BoundingBoxType | ("piece" | "structure"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureSpawnOverride$BoundingBoxType_ = $StructureSpawnOverride$BoundingBoxType$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$PosRuleTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PosRuleTest$$Type = ($PosRuleTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PosRuleTest_ = $PosRuleTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureSpawnOverride" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureSpawnOverride$$Type = ($StructureSpawnOverride);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureSpawnOverride_ = $StructureSpawnOverride$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplate$StructureEntityInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplate$StructureEntityInfo$$Type = ($StructureTemplate$StructureEntityInfo);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplate$StructureEntityInfo_ = $StructureTemplate$StructureEntityInfo$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$OceanRuinStructure$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $OceanRuinStructure$Type$$Type = ($OceanRuinStructure$Type | ("warm" | "cold"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $OceanRuinStructure$Type_ = $OceanRuinStructure$Type$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$DesertPyramidStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DesertPyramidStructure$$Type = ($DesertPyramidStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DesertPyramidStructure_ = $DesertPyramidStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$RuleBlockEntityModifierType" {
import { $AppendStatic } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$AppendStatic"
import { $AppendLoot } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$AppendLoot"
import { $Passthrough } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$Passthrough"
import { $RuleBlockEntityModifier, $RuleBlockEntityModifier$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$RuleBlockEntityModifier"
import { $Clear } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$Clear"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"

export interface $RuleBlockEntityModifierType<P extends $RuleBlockEntityModifier> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.RuleBlockEntityModifier
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.RuleBlockEntityModifierTag
}

export namespace $RuleBlockEntityModifierType {
const APPEND_LOOT: $RuleBlockEntityModifierType<$AppendLoot>
const APPEND_STATIC: $RuleBlockEntityModifierType<$AppendStatic>
const CLEAR: $RuleBlockEntityModifierType<$Clear>
const PASSTHROUGH: $RuleBlockEntityModifierType<$Passthrough>
}
export abstract class $RuleBlockEntityModifierType$$Static<P extends $RuleBlockEntityModifier> implements $RuleBlockEntityModifierType<P> {
static readonly "APPEND_LOOT": $RuleBlockEntityModifierType<$AppendLoot>
static readonly "APPEND_STATIC": $RuleBlockEntityModifierType<$AppendStatic>
static readonly "CLEAR": $RuleBlockEntityModifierType<$Clear>
static readonly "PASSTHROUGH": $RuleBlockEntityModifierType<$Passthrough>

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuleBlockEntityModifierType$$Type<P extends $RuleBlockEntityModifier> = ($RuleBlockEntityModifierType<P> | Special.RuleBlockEntityModifier | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuleBlockEntityModifierType_<P extends $RuleBlockEntityModifier> = $RuleBlockEntityModifierType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$PosAlwaysTrueTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PosAlwaysTrueTest$$Type = ($PosAlwaysTrueTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PosAlwaysTrueTest_ = $PosAlwaysTrueTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$RuleBlockEntityModifier" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuleBlockEntityModifier$$Type = ($RuleBlockEntityModifier);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuleBlockEntityModifier_ = $RuleBlockEntityModifier$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockRotProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlockRotProcessor$$Type = ($BlockRotProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlockRotProcessor_ = $BlockRotProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$PosRuleTestType" {
import { $PosRuleTest, $PosRuleTest$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$PosRuleTest"
import { $LinearPosTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$LinearPosTest"
import { $AxisAlignedLinearPosTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$AxisAlignedLinearPosTest"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $PosAlwaysTrueTest } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$PosAlwaysTrueTest"

export interface $PosRuleTestType<P extends $PosRuleTest> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.PosRuleTest
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PosRuleTestTag
}

export namespace $PosRuleTestType {
const ALWAYS_TRUE_TEST: $PosRuleTestType<$PosAlwaysTrueTest>
const AXIS_ALIGNED_LINEAR_POS_TEST: $PosRuleTestType<$AxisAlignedLinearPosTest>
const LINEAR_POS_TEST: $PosRuleTestType<$LinearPosTest>
function register<P extends $PosRuleTest>(string0: string, codec1: $Codec$$Type<P>): $PosRuleTestType<P>
}
export abstract class $PosRuleTestType$$Static<P extends $PosRuleTest> implements $PosRuleTestType<P> {
static readonly "ALWAYS_TRUE_TEST": $PosRuleTestType<$PosAlwaysTrueTest>
static readonly "AXIS_ALIGNED_LINEAR_POS_TEST": $PosRuleTestType<$AxisAlignedLinearPosTest>
static readonly "LINEAR_POS_TEST": $PosRuleTestType<$LinearPosTest>

static "register"<P extends $PosRuleTest>(string0: string, codec1: $Codec$$Type<P>): $PosRuleTestType<P>
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PosRuleTestType$$Type<P extends $PosRuleTest> = ($PosRuleTestType<P> | Special.PosRuleTest | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PosRuleTestType_<P extends $PosRuleTest> = $PosRuleTestType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$SwampHutStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SwampHutStructure$$Type = ($SwampHutStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SwampHutStructure_ = $SwampHutStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pieces/$StructurePiecesBuilder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePiecesBuilder$$Type = ($StructurePiecesBuilder);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePiecesBuilder_ = $StructurePiecesBuilder$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RandomBlockMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RandomBlockMatchTest$$Type = ($RandomBlockMatchTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RandomBlockMatchTest_ = $RandomBlockMatchTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplate$Palette" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplate$Palette$$Type = ($StructureTemplate$Palette);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplate$Palette_ = $StructureTemplate$Palette$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$Structure$GenerationStub" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Structure$GenerationStub$$Type = ($Structure$GenerationStub);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Structure$GenerationStub_ = $Structure$GenerationStub$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$MineshaftStructure$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MineshaftStructure$Type$$Type = ($MineshaftStructure$Type | ("normal" | "mesa"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MineshaftStructure$Type_ = $MineshaftStructure$Type$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$AppendLoot" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AppendLoot$$Type = ($AppendLoot);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AppendLoot_ = $AppendLoot$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$TerrainAdjustment" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $TerrainAdjustment$$Type = ($TerrainAdjustment | ("none" | "bury" | "beard_thin" | "beard_box"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $TerrainAdjustment_ = $TerrainAdjustment$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$BoundingBox" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BoundingBox$$Type = ($BoundingBox);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BoundingBox_ = $BoundingBox$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$JigsawReplacementProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $JigsawReplacementProcessor$$Type = ($JigsawReplacementProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $JigsawReplacementProcessor_ = $JigsawReplacementProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacementType" {
import { $ConcentricRingsStructurePlacement } from "packages/net/minecraft/world/level/levelgen/structure/placement/$ConcentricRingsStructurePlacement"
import { $StructurePlacement, $StructurePlacement$$Type } from "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacement"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $RandomSpreadStructurePlacement } from "packages/net/minecraft/world/level/levelgen/structure/placement/$RandomSpreadStructurePlacement"

export interface $StructurePlacementType<SP extends $StructurePlacement> {
"codec"(): $Codec<SP>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePlacement
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePlacementTag
}

export namespace $StructurePlacementType {
const CONCENTRIC_RINGS: $StructurePlacementType<$ConcentricRingsStructurePlacement>
const RANDOM_SPREAD: $StructurePlacementType<$RandomSpreadStructurePlacement>
}
export abstract class $StructurePlacementType$$Static<SP extends $StructurePlacement> implements $StructurePlacementType<SP> {
static readonly "CONCENTRIC_RINGS": $StructurePlacementType<$ConcentricRingsStructurePlacement>
static readonly "RANDOM_SPREAD": $StructurePlacementType<$RandomSpreadStructurePlacement>

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePlacementType$$Type<SP extends $StructurePlacement> = ($StructurePlacementType<SP> | Special.WorldgenStructurePlacement | (() => $Codec$$Type<SP>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePlacementType_<SP extends $StructurePlacement> = $StructurePlacementType$$Type<SP>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$IglooStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $IglooStructure$$Type = ($IglooStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $IglooStructure_ = $IglooStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$FeaturePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $FeaturePoolElement$$Type = ($FeaturePoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $FeaturePoolElement_ = $FeaturePoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$RuinedPortalStructure$Setup" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuinedPortalStructure$Setup$$Type = ($RuinedPortalStructure$Setup);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuinedPortalStructure$Setup_ = $RuinedPortalStructure$Setup$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$ProtectedBlockProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ProtectedBlockProcessor$$Type = ($ProtectedBlockProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ProtectedBlockProcessor_ = $ProtectedBlockProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessorList" {
import { $StructureProcessor, $StructureProcessor$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessor"
import { $List, $List$$Type } from "packages/java/util/$List"

export class $StructureProcessorList {
"list": $List<$StructureProcessor>

constructor(list0: $List$$Type<$StructureProcessor$$Type>)

public "list"(): $List<$StructureProcessor>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenProcessorList
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenProcessorListTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureProcessorList$$Type = ($StructureProcessorList | Special.WorldgenProcessorList);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureProcessorList_ = $StructureProcessorList$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureCheckResult" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureCheckResult$$Type = ($StructureCheckResult | ("start_present" | "start_not_present" | "chunk_load_needed"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureCheckResult_ = $StructureCheckResult$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$SinglePieceStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SinglePieceStructure$$Type = ($SinglePieceStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SinglePieceStructure_ = $SinglePieceStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$BuriedTreasureStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BuriedTreasureStructure$$Type = ($BuriedTreasureStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BuriedTreasureStructure_ = $BuriedTreasureStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$ConcentricRingsStructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ConcentricRingsStructurePlacement$$Type = ($ConcentricRingsStructurePlacement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ConcentricRingsStructurePlacement_ = $ConcentricRingsStructurePlacement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructurePlaceSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePlaceSettings$$Type = ($StructurePlaceSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePlaceSettings_ = $StructurePlaceSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$StructurePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePoolElement$$Type = ($StructurePoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePoolElement_ = $StructurePoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacement$FrequencyReductionMethod" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePlacement$FrequencyReductionMethod$$Type = ($StructurePlacement$FrequencyReductionMethod | ("default" | "legacy_type_1" | "legacy_type_2" | "legacy_type_3"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePlacement$FrequencyReductionMethod_ = $StructurePlacement$FrequencyReductionMethod$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$LinearPosTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LinearPosTest$$Type = ($LinearPosTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LinearPosTest_ = $LinearPosTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureCheck" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureCheck$$Type = ($StructureCheck);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureCheck_ = $StructureCheck$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlockMatchTest$$Type = ($BlockMatchTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlockMatchTest_ = $BlockMatchTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$NopProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NopProcessor$$Type = ($NopProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NopProcessor_ = $NopProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$StructureTemplatePool" {
import { $StructureTemplatePool$Projection$$Type } from "packages/net/minecraft/world/level/levelgen/structure/pools/$StructureTemplatePool$Projection"
import { $TemplatePoolAccess } from "packages/blusunrize/immersiveengineering/mixin/accessors/$TemplatePoolAccess"
import { $StructurePoolElement, $StructurePoolElement$$Type } from "packages/net/minecraft/world/level/levelgen/structure/pools/$StructurePoolElement"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $ObjectArrayList, $ObjectArrayList$$Type } from "packages/it/unimi/dsi/fastutil/objects/$ObjectArrayList"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $Function$$Type } from "packages/java/util/function/$Function"
import { $StructureTemplateManager$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplateManager"
import { $StructureTemplatePoolAccessor } from "packages/net/blay09/mods/waystones/mixin/$StructureTemplatePoolAccessor"
import { $List, $List$$Type } from "packages/java/util/$List"
import { $RandomSource$$Type } from "packages/net/minecraft/util/$RandomSource"
import { $Pair, $Pair$$Type } from "packages/com/mojang/datafixers/util/$Pair"

export class $StructureTemplatePool implements $StructureTemplatePoolAccessor, $TemplatePoolAccess {
static readonly "CODEC": $Codec<$Holder<$StructureTemplatePool>>
static readonly "DIRECT_CODEC": $Codec<$StructureTemplatePool>

constructor(holder0: $Holder$$Type<$StructureTemplatePool$$Type>, list1: $List$$Type<$Pair$$Type<$StructurePoolElement$$Type, integer>>)
constructor(holder0: $Holder$$Type<$StructureTemplatePool$$Type>, list1: $List$$Type<$Pair$$Type<$Function$$Type<$StructureTemplatePool$Projection$$Type, $StructurePoolElement$$Type>, integer>>, projection2: $StructureTemplatePool$Projection$$Type)

public "getFallback"(): $Holder<$StructureTemplatePool>
public "getMaxSize"(structureTemplateManager0: $StructureTemplateManager$$Type): integer
public "getRandomTemplate"(randomSource0: $RandomSource$$Type): $StructurePoolElement
public "getShuffledTemplates"(randomSource0: $RandomSource$$Type): $List<$StructurePoolElement>
public "size"(): integer
get "rawTemplates"(): $List<$Pair<$StructurePoolElement, integer>>
set "rawTemplates"(value: $List$$Type<$Pair$$Type<$StructurePoolElement$$Type, integer>>)
get "templates"(): $ObjectArrayList<$StructurePoolElement>
set "templates"(value: $ObjectArrayList$$Type<$StructurePoolElement$$Type>)
get "fallback"(): $Holder<$StructureTemplatePool>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenTemplatePool
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenTemplatePoolTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplatePool$$Type = ($StructureTemplatePool | Special.WorldgenTemplatePool);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplatePool_ = $StructureTemplatePool$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pieces/$PiecesContainer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $PiecesContainer$$Type = ($PiecesContainer);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $PiecesContainer_ = $PiecesContainer$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$OceanRuinStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $OceanRuinStructure$$Type = ($OceanRuinStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $OceanRuinStructure_ = $OceanRuinStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$LavaSubmergedBlockProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LavaSubmergedBlockProcessor$$Type = ($LavaSubmergedBlockProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LavaSubmergedBlockProcessor_ = $LavaSubmergedBlockProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$StrongholdStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StrongholdStructure$$Type = ($StrongholdStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StrongholdStructure_ = $StrongholdStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$JungleTempleStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $JungleTempleStructure$$Type = ($JungleTempleStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $JungleTempleStructure_ = $JungleTempleStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RandomBlockStateMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RandomBlockStateMatchTest$$Type = ($RandomBlockStateMatchTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RandomBlockStateMatchTest_ = $RandomBlockStateMatchTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$RuinedPortalPiece$VerticalPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuinedPortalPiece$VerticalPlacement$$Type = ($RuinedPortalPiece$VerticalPlacement | ("on_land_surface" | "partly_buried" | "on_ocean_floor" | "in_mountain" | "underground" | "in_nether"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuinedPortalPiece$VerticalPlacement_ = $RuinedPortalPiece$VerticalPlacement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$GravityProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $GravityProcessor$$Type = ($GravityProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $GravityProcessor_ = $GravityProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$StructurePoolElementType" {
import { $FeaturePoolElement } from "packages/net/minecraft/world/level/levelgen/structure/pools/$FeaturePoolElement"
import { $SinglePoolElement } from "packages/net/minecraft/world/level/levelgen/structure/pools/$SinglePoolElement"
import { $LegacySinglePoolElement } from "packages/net/minecraft/world/level/levelgen/structure/pools/$LegacySinglePoolElement"
import { $StructurePoolElement, $StructurePoolElement$$Type } from "packages/net/minecraft/world/level/levelgen/structure/pools/$StructurePoolElement"
import { $EmptyPoolElement } from "packages/net/minecraft/world/level/levelgen/structure/pools/$EmptyPoolElement"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $ListPoolElement } from "packages/net/minecraft/world/level/levelgen/structure/pools/$ListPoolElement"

export interface $StructurePoolElementType<P extends $StructurePoolElement> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePoolElement
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePoolElementTag
}

export namespace $StructurePoolElementType {
const EMPTY: $StructurePoolElementType<$EmptyPoolElement>
const FEATURE: $StructurePoolElementType<$FeaturePoolElement>
const LEGACY: $StructurePoolElementType<$LegacySinglePoolElement>
const LIST: $StructurePoolElementType<$ListPoolElement>
const SINGLE: $StructurePoolElementType<$SinglePoolElement>
function register<P extends $StructurePoolElement>(string0: string, codec1: $Codec$$Type<P>): $StructurePoolElementType<P>
}
export abstract class $StructurePoolElementType$$Static<P extends $StructurePoolElement> implements $StructurePoolElementType<P> {
static readonly "EMPTY": $StructurePoolElementType<$EmptyPoolElement>
static readonly "FEATURE": $StructurePoolElementType<$FeaturePoolElement>
static readonly "LEGACY": $StructurePoolElementType<$LegacySinglePoolElement>
static readonly "LIST": $StructurePoolElementType<$ListPoolElement>
static readonly "SINGLE": $StructurePoolElementType<$SinglePoolElement>

static "register"<P extends $StructurePoolElement>(string0: string, codec1: $Codec$$Type<P>): $StructurePoolElementType<P>
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePoolElementType$$Type<P extends $StructurePoolElement> = ($StructurePoolElementType<P> | Special.WorldgenStructurePoolElement | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePoolElementType_<P extends $StructurePoolElement> = $StructurePoolElementType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$Structure$StructureSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Structure$StructureSettings$$Type = ($Structure$StructureSettings);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Structure$StructureSettings_ = $Structure$StructureSettings$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$Clear" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Clear$$Type = ($Clear);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Clear_ = $Clear$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pieces/$StructurePieceSerializationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePieceSerializationContext$$Type = ($StructurePieceSerializationContext);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePieceSerializationContext_ = $StructurePieceSerializationContext$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$JigsawStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $JigsawStructure$$Type = ($JigsawStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $JigsawStructure_ = $JigsawStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RuleProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuleProcessor$$Type = ($RuleProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuleProcessor_ = $RuleProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$ShipwreckStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ShipwreckStructure$$Type = ($ShipwreckStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ShipwreckStructure_ = $ShipwreckStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$Structure" {
import { $BoundingBox, $BoundingBox$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$BoundingBox"
import { $HolderSet } from "packages/net/minecraft/core/$HolderSet"
import { $ChunkGenerator$$Type } from "packages/net/minecraft/world/level/chunk/$ChunkGenerator"
import { $GenerationStep$Decoration } from "packages/net/minecraft/world/level/levelgen/$GenerationStep$Decoration"
import { $RandomState$$Type } from "packages/net/minecraft/world/level/levelgen/$RandomState"
import { $WorldGenLevel$$Type } from "packages/net/minecraft/world/level/$WorldGenLevel"
import { $Codec } from "packages/com/mojang/serialization/$Codec"
import { $StructureSpawnOverride } from "packages/net/minecraft/world/level/levelgen/structure/$StructureSpawnOverride"
import { $Function$$Type } from "packages/java/util/function/$Function"
import { $ModifiableStructureInfo } from "packages/net/minecraftforge/common/world/$ModifiableStructureInfo"
import { $RandomSource$$Type } from "packages/net/minecraft/util/$RandomSource"
import { $Biome, $Biome$$Type } from "packages/net/minecraft/world/level/biome/$Biome"
import { $Structure$GenerationStub } from "packages/net/minecraft/world/level/levelgen/structure/$Structure$GenerationStub"
import { $MobCategory } from "packages/net/minecraft/world/entity/$MobCategory"
import { $PiecesContainer$$Type } from "packages/net/minecraft/world/level/levelgen/structure/pieces/$PiecesContainer"
import { $ChunkPos$$Type } from "packages/net/minecraft/world/level/$ChunkPos"
import { $RecordCodecBuilder } from "packages/com/mojang/serialization/codecs/$RecordCodecBuilder"
import { $LevelHeightAccessor$$Type } from "packages/net/minecraft/world/level/$LevelHeightAccessor"
import { $StructureStart } from "packages/net/minecraft/world/level/levelgen/structure/$StructureStart"
import { $Predicate$$Type } from "packages/java/util/function/$Predicate"
import { $StructureType } from "packages/net/minecraft/world/level/levelgen/structure/$StructureType"
import { $RecordCodecBuilder$Instance$$Type } from "packages/com/mojang/serialization/codecs/$RecordCodecBuilder$Instance"
import { $RegistryAccess$$Type } from "packages/net/minecraft/core/$RegistryAccess"
import { $TerrainAdjustment } from "packages/net/minecraft/world/level/levelgen/structure/$TerrainAdjustment"
import { $Holder, $Holder$$Type } from "packages/net/minecraft/core/$Holder"
import { $StructureTemplateManager$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplateManager"
import { $BiomeSource$$Type } from "packages/net/minecraft/world/level/biome/$BiomeSource"
import { $Optional } from "packages/java/util/$Optional"
import { $StructureManager$$Type } from "packages/net/minecraft/world/level/$StructureManager"
import { $Structure$GenerationContext$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$Structure$GenerationContext"
import { $Structure$StructureSettings, $Structure$StructureSettings$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$Structure$StructureSettings"
import { $Map } from "packages/java/util/$Map"

export class $Structure {
static readonly "CODEC": $Codec<$Holder<$Structure>>
static readonly "DIRECT_CODEC": $Codec<$Structure>

public "adjustBoundingBox"(boundingBox0: $BoundingBox$$Type): $BoundingBox
public "afterPlace"(worldGenLevel0: $WorldGenLevel$$Type, structureManager1: $StructureManager$$Type, chunkGenerator2: $ChunkGenerator$$Type, randomSource3: $RandomSource$$Type, boundingBox4: $BoundingBox$$Type, chunkPos5: $ChunkPos$$Type, piecesContainer6: $PiecesContainer$$Type): void
public "biomes"(): $HolderSet<$Biome>
public "findValidGenerationPoint"(generationContext0: $Structure$GenerationContext$$Type): $Optional<$Structure$GenerationStub>
public "generate"(registryAccess0: $RegistryAccess$$Type, chunkGenerator1: $ChunkGenerator$$Type, biomeSource2: $BiomeSource$$Type, randomState3: $RandomState$$Type, structureTemplateManager4: $StructureTemplateManager$$Type, long5: long, chunkPos6: $ChunkPos$$Type, int7: integer, levelHeightAccessor8: $LevelHeightAccessor$$Type, predicate9: $Predicate$$Type<$Holder$$Type<$Biome$$Type>>): $StructureStart
public "getModifiedStructureSettings"(): $Structure$StructureSettings
public "modifiableStructureInfo"(): $ModifiableStructureInfo
public static "settingsCodec"<S extends $Structure>(instance0: $RecordCodecBuilder$Instance$$Type<S>): $RecordCodecBuilder<S, $Structure$StructureSettings>
public static "simpleCodec"<S extends $Structure>(function0: $Function$$Type<$Structure$StructureSettings$$Type, S>): $Codec<S>
public "spawnOverrides"(): $Map<$MobCategory, $StructureSpawnOverride>
public "step"(): $GenerationStep$Decoration
public "terrainAdaptation"(): $TerrainAdjustment
public "type"(): $StructureType<any>
get "modifiedStructureSettings"(): $Structure$StructureSettings
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructure
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Structure$$Type = ($Structure | Special.WorldgenStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Structure_ = $Structure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureType" {
import { $RuinedPortalStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$RuinedPortalStructure"
import { $StrongholdStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$StrongholdStructure"
import { $OceanMonumentStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$OceanMonumentStructure"
import { $IglooStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$IglooStructure"
import { $JungleTempleStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$JungleTempleStructure"
import { $WoodlandMansionStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$WoodlandMansionStructure"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $EndCityStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$EndCityStructure"
import { $MineshaftStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$MineshaftStructure"
import { $BuriedTreasureStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$BuriedTreasureStructure"
import { $NetherFossilStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$NetherFossilStructure"
import { $ShipwreckStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$ShipwreckStructure"
import { $Structure, $Structure$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$Structure"
import { $JigsawStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$JigsawStructure"
import { $SwampHutStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$SwampHutStructure"
import { $DesertPyramidStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$DesertPyramidStructure"
import { $NetherFortressStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$NetherFortressStructure"
import { $OceanRuinStructure } from "packages/net/minecraft/world/level/levelgen/structure/structures/$OceanRuinStructure"

export interface $StructureType<S extends $Structure> {
"codec"(): $Codec<S>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureTypeTag
}

export namespace $StructureType {
const BURIED_TREASURE: $StructureType<$BuriedTreasureStructure>
const DESERT_PYRAMID: $StructureType<$DesertPyramidStructure>
const END_CITY: $StructureType<$EndCityStructure>
const FORTRESS: $StructureType<$NetherFortressStructure>
const IGLOO: $StructureType<$IglooStructure>
const JIGSAW: $StructureType<$JigsawStructure>
const JUNGLE_TEMPLE: $StructureType<$JungleTempleStructure>
const MINESHAFT: $StructureType<$MineshaftStructure>
const NETHER_FOSSIL: $StructureType<$NetherFossilStructure>
const OCEAN_MONUMENT: $StructureType<$OceanMonumentStructure>
const OCEAN_RUIN: $StructureType<$OceanRuinStructure>
const RUINED_PORTAL: $StructureType<$RuinedPortalStructure>
const SHIPWRECK: $StructureType<$ShipwreckStructure>
const STRONGHOLD: $StructureType<$StrongholdStructure>
const SWAMP_HUT: $StructureType<$SwampHutStructure>
const WOODLAND_MANSION: $StructureType<$WoodlandMansionStructure>
}
export abstract class $StructureType$$Static<S extends $Structure> implements $StructureType<S> {
static readonly "BURIED_TREASURE": $StructureType<$BuriedTreasureStructure>
static readonly "DESERT_PYRAMID": $StructureType<$DesertPyramidStructure>
static readonly "END_CITY": $StructureType<$EndCityStructure>
static readonly "FORTRESS": $StructureType<$NetherFortressStructure>
static readonly "IGLOO": $StructureType<$IglooStructure>
static readonly "JIGSAW": $StructureType<$JigsawStructure>
static readonly "JUNGLE_TEMPLE": $StructureType<$JungleTempleStructure>
static readonly "MINESHAFT": $StructureType<$MineshaftStructure>
static readonly "NETHER_FOSSIL": $StructureType<$NetherFossilStructure>
static readonly "OCEAN_MONUMENT": $StructureType<$OceanMonumentStructure>
static readonly "OCEAN_RUIN": $StructureType<$OceanRuinStructure>
static readonly "RUINED_PORTAL": $StructureType<$RuinedPortalStructure>
static readonly "SHIPWRECK": $StructureType<$ShipwreckStructure>
static readonly "STRONGHOLD": $StructureType<$StrongholdStructure>
static readonly "SWAMP_HUT": $StructureType<$SwampHutStructure>
static readonly "WOODLAND_MANSION": $StructureType<$WoodlandMansionStructure>

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureType$$Type<S extends $Structure> = ($StructureType<S> | Special.WorldgenStructureType | (() => $Codec$$Type<S>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureType_<S extends $Structure> = $StructureType$$Type<S>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureSet$StructureSelectionEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureSet$StructureSelectionEntry$$Type = ($StructureSet$StructureSelectionEntry);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureSet$StructureSelectionEntry_ = $StructureSet$StructureSelectionEntry$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$NetherFortressStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $NetherFortressStructure$$Type = ($NetherFortressStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $NetherFortressStructure_ = $NetherFortressStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pieces/$StructurePieceType" {
import { $StructurePieceSerializationContext, $StructurePieceSerializationContext$$Type } from "packages/net/minecraft/world/level/levelgen/structure/pieces/$StructurePieceSerializationContext"
import { $CompoundTag, $CompoundTag$$Type } from "packages/net/minecraft/nbt/$CompoundTag"
import { $StructurePiece, $StructurePiece$$Type } from "packages/net/minecraft/world/level/levelgen/structure/$StructurePiece"

export interface $StructurePieceType {
"load"(structurePieceSerializationContext0: $StructurePieceSerializationContext$$Type, compoundTag1: $CompoundTag$$Type): $StructurePiece
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePiece
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePieceTag
}

export namespace $StructurePieceType {
const BURIED_TREASURE_PIECE: $StructurePieceType
const DESERT_PYRAMID_PIECE: $StructurePieceType
const END_CITY_PIECE: $StructurePieceType
const IGLOO: $StructurePieceType
const JIGSAW: $StructurePieceType
const JUNGLE_PYRAMID_PIECE: $StructurePieceType
const MINE_SHAFT_CORRIDOR: $StructurePieceType
const MINE_SHAFT_CROSSING: $StructurePieceType
const MINE_SHAFT_ROOM: $StructurePieceType
const MINE_SHAFT_STAIRS: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_CROSSING: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_END_FILLER: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_STRAIGHT: $StructurePieceType
const NETHER_FORTRESS_CASTLE_CORRIDOR_STAIRS: $StructurePieceType
const NETHER_FORTRESS_CASTLE_CORRIDOR_T_BALCONY: $StructurePieceType
const NETHER_FORTRESS_CASTLE_ENTRANCE: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_CROSSING: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_LEFT_TURN: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_RIGHT_TURN: $StructurePieceType
const NETHER_FORTRESS_CASTLE_STALK_ROOM: $StructurePieceType
const NETHER_FORTRESS_MONSTER_THRONE: $StructurePieceType
const NETHER_FORTRESS_ROOM_CROSSING: $StructurePieceType
const NETHER_FORTRESS_STAIRS_ROOM: $StructurePieceType
const NETHER_FORTRESS_START: $StructurePieceType
const NETHER_FOSSIL: $StructurePieceType
const OCEAN_MONUMENT_BUILDING: $StructurePieceType
const OCEAN_MONUMENT_CORE_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_XY_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_X_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_YZ_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_Y_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_Z_ROOM: $StructurePieceType
const OCEAN_MONUMENT_ENTRY_ROOM: $StructurePieceType
const OCEAN_MONUMENT_PENTHOUSE: $StructurePieceType
const OCEAN_MONUMENT_SIMPLE_ROOM: $StructurePieceType
const OCEAN_MONUMENT_SIMPLE_TOP_ROOM: $StructurePieceType
const OCEAN_MONUMENT_WING_ROOM: $StructurePieceType
const OCEAN_RUIN: $StructurePieceType
const RUINED_PORTAL: $StructurePieceType
const SHIPWRECK_PIECE: $StructurePieceType
const STRONGHOLD_CHEST_CORRIDOR: $StructurePieceType
const STRONGHOLD_FILLER_CORRIDOR: $StructurePieceType
const STRONGHOLD_FIVE_CROSSING: $StructurePieceType
const STRONGHOLD_LEFT_TURN: $StructurePieceType
const STRONGHOLD_LIBRARY: $StructurePieceType
const STRONGHOLD_PORTAL_ROOM: $StructurePieceType
const STRONGHOLD_PRISON_HALL: $StructurePieceType
const STRONGHOLD_RIGHT_TURN: $StructurePieceType
const STRONGHOLD_ROOM_CROSSING: $StructurePieceType
const STRONGHOLD_STAIRS_DOWN: $StructurePieceType
const STRONGHOLD_START: $StructurePieceType
const STRONGHOLD_STRAIGHT: $StructurePieceType
const STRONGHOLD_STRAIGHT_STAIRS_DOWN: $StructurePieceType
const SWAMPLAND_HUT: $StructurePieceType
const WOODLAND_MANSION_PIECE: $StructurePieceType
}
export abstract class $StructurePieceType$$Static implements $StructurePieceType {
static readonly "BURIED_TREASURE_PIECE": $StructurePieceType
static readonly "DESERT_PYRAMID_PIECE": $StructurePieceType
static readonly "END_CITY_PIECE": $StructurePieceType
static readonly "IGLOO": $StructurePieceType
static readonly "JIGSAW": $StructurePieceType
static readonly "JUNGLE_PYRAMID_PIECE": $StructurePieceType
static readonly "MINE_SHAFT_CORRIDOR": $StructurePieceType
static readonly "MINE_SHAFT_CROSSING": $StructurePieceType
static readonly "MINE_SHAFT_ROOM": $StructurePieceType
static readonly "MINE_SHAFT_STAIRS": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_END_FILLER": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_STRAIGHT": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_CORRIDOR_STAIRS": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_CORRIDOR_T_BALCONY": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_ENTRANCE": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_LEFT_TURN": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_RIGHT_TURN": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_STALK_ROOM": $StructurePieceType
static readonly "NETHER_FORTRESS_MONSTER_THRONE": $StructurePieceType
static readonly "NETHER_FORTRESS_ROOM_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_STAIRS_ROOM": $StructurePieceType
static readonly "NETHER_FORTRESS_START": $StructurePieceType
static readonly "NETHER_FOSSIL": $StructurePieceType
static readonly "OCEAN_MONUMENT_BUILDING": $StructurePieceType
static readonly "OCEAN_MONUMENT_CORE_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_XY_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_X_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_YZ_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_Y_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_Z_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_ENTRY_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_PENTHOUSE": $StructurePieceType
static readonly "OCEAN_MONUMENT_SIMPLE_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_SIMPLE_TOP_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_WING_ROOM": $StructurePieceType
static readonly "OCEAN_RUIN": $StructurePieceType
static readonly "RUINED_PORTAL": $StructurePieceType
static readonly "SHIPWRECK_PIECE": $StructurePieceType
static readonly "STRONGHOLD_CHEST_CORRIDOR": $StructurePieceType
static readonly "STRONGHOLD_FILLER_CORRIDOR": $StructurePieceType
static readonly "STRONGHOLD_FIVE_CROSSING": $StructurePieceType
static readonly "STRONGHOLD_LEFT_TURN": $StructurePieceType
static readonly "STRONGHOLD_LIBRARY": $StructurePieceType
static readonly "STRONGHOLD_PORTAL_ROOM": $StructurePieceType
static readonly "STRONGHOLD_PRISON_HALL": $StructurePieceType
static readonly "STRONGHOLD_RIGHT_TURN": $StructurePieceType
static readonly "STRONGHOLD_ROOM_CROSSING": $StructurePieceType
static readonly "STRONGHOLD_STAIRS_DOWN": $StructurePieceType
static readonly "STRONGHOLD_START": $StructurePieceType
static readonly "STRONGHOLD_STRAIGHT": $StructurePieceType
static readonly "STRONGHOLD_STRAIGHT_STAIRS_DOWN": $StructurePieceType
static readonly "SWAMPLAND_HUT": $StructurePieceType
static readonly "WOODLAND_MANSION_PIECE": $StructurePieceType

}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePieceType$$Type = ($StructurePieceType | Special.WorldgenStructurePiece | ((arg0: $StructurePieceSerializationContext, arg1: $CompoundTag) => $StructurePiece$$Type));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePieceType_ = $StructurePieceType$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$ListPoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $ListPoolElement$$Type = ($ListPoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $ListPoolElement_ = $ListPoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$StructurePlacement$ExclusionZone" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePlacement$ExclusionZone$$Type = ($StructurePlacement$ExclusionZone);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePlacement$ExclusionZone_ = $StructurePlacement$ExclusionZone$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockStateMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlockStateMatchTest$$Type = ($BlockStateMatchTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlockStateMatchTest_ = $BlockStateMatchTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlackstoneReplaceProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $BlackstoneReplaceProcessor$$Type = ($BlackstoneReplaceProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $BlackstoneReplaceProcessor_ = $BlackstoneReplaceProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$Passthrough" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Passthrough$$Type = ($Passthrough);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Passthrough_ = $Passthrough$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructurePiece" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePiece$$Type = ($StructurePiece);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePiece_ = $StructurePiece$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureProcessor$$Type = ($StructureProcessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureProcessor_ = $StructureProcessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureTemplate" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureTemplate$$Type = ($StructureTemplate);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureTemplate_ = $StructureTemplate$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$LegacySinglePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $LegacySinglePoolElement$$Type = ($LegacySinglePoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $LegacySinglePoolElement_ = $LegacySinglePoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/placement/$RandomSpreadType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RandomSpreadType$$Type = ($RandomSpreadType | ("linear" | "triangular"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RandomSpreadType_ = $RandomSpreadType$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RuleTest" {
import { $CompoundTag$$Type } from "packages/net/minecraft/nbt/$CompoundTag"

/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuleTest$$Type = ($RuleTest | $CompoundTag$$Type);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuleTest_ = $RuleTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$RuinedPortalStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $RuinedPortalStructure$$Type = ($RuinedPortalStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $RuinedPortalStructure_ = $RuinedPortalStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/structures/$MineshaftStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $MineshaftStructure$$Type = ($MineshaftStructure);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $MineshaftStructure_ = $MineshaftStructure$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$EmptyPoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $EmptyPoolElement$$Type = ($EmptyPoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $EmptyPoolElement_ = $EmptyPoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$AxisAlignedLinearPosTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AxisAlignedLinearPosTest$$Type = ($AxisAlignedLinearPosTest);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AxisAlignedLinearPosTest_ = $AxisAlignedLinearPosTest$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructurePieceAccessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructurePieceAccessor$$Type = ($StructurePieceAccessor);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructurePieceAccessor_ = $StructurePieceAccessor$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/pools/$SinglePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SinglePoolElement$$Type = ($SinglePoolElement);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SinglePoolElement_ = $SinglePoolElement$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity/$AppendStatic" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $AppendStatic$$Type = ($AppendStatic);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $AppendStatic_ = $AppendStatic$$Type;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessorType" {
import { $JigsawReplacementProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$JigsawReplacementProcessor"
import { $GravityProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$GravityProcessor"
import { $StructureProcessorList } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessorList"
import { $BlockAgeProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockAgeProcessor"
import { $BlockIgnoreProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockIgnoreProcessor"
import { $BlackstoneReplaceProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlackstoneReplaceProcessor"
import { $Codec, $Codec$$Type } from "packages/com/mojang/serialization/$Codec"
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $BlockRotProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$BlockRotProcessor"
import { $ProtectedBlockProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$ProtectedBlockProcessor"
import { $StructureProcessor, $StructureProcessor$$Type } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$StructureProcessor"
import { $NopProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$NopProcessor"
import { $CappedProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$CappedProcessor"
import { $LavaSubmergedBlockProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$LavaSubmergedBlockProcessor"
import { $RuleProcessor } from "packages/net/minecraft/world/level/levelgen/structure/templatesystem/$RuleProcessor"

export interface $StructureProcessorType<P extends $StructureProcessor> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureProcessor
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureProcessorTag
}

export namespace $StructureProcessorType {
const BLACKSTONE_REPLACE: $StructureProcessorType<$BlackstoneReplaceProcessor>
const BLOCK_AGE: $StructureProcessorType<$BlockAgeProcessor>
const BLOCK_IGNORE: $StructureProcessorType<$BlockIgnoreProcessor>
const BLOCK_ROT: $StructureProcessorType<$BlockRotProcessor>
const CAPPED: $StructureProcessorType<$CappedProcessor>
const DIRECT_CODEC: $Codec<$StructureProcessorList>
const GRAVITY: $StructureProcessorType<$GravityProcessor>
const JIGSAW_REPLACEMENT: $StructureProcessorType<$JigsawReplacementProcessor>
const LAVA_SUBMERGED_BLOCK: $StructureProcessorType<$LavaSubmergedBlockProcessor>
const LIST_CODEC: $Codec<$Holder<$StructureProcessorList>>
const LIST_OBJECT_CODEC: $Codec<$StructureProcessorList>
const NOP: $StructureProcessorType<$NopProcessor>
const PROTECTED_BLOCKS: $StructureProcessorType<$ProtectedBlockProcessor>
const RULE: $StructureProcessorType<$RuleProcessor>
const SINGLE_CODEC: $Codec<$StructureProcessor>
function register<P extends $StructureProcessor>(string0: string, codec1: $Codec$$Type<P>): $StructureProcessorType<P>
}
export abstract class $StructureProcessorType$$Static<P extends $StructureProcessor> implements $StructureProcessorType<P> {
static readonly "BLACKSTONE_REPLACE": $StructureProcessorType<$BlackstoneReplaceProcessor>
static readonly "BLOCK_AGE": $StructureProcessorType<$BlockAgeProcessor>
static readonly "BLOCK_IGNORE": $StructureProcessorType<$BlockIgnoreProcessor>
static readonly "BLOCK_ROT": $StructureProcessorType<$BlockRotProcessor>
static readonly "CAPPED": $StructureProcessorType<$CappedProcessor>
static readonly "DIRECT_CODEC": $Codec<$StructureProcessorList>
static readonly "GRAVITY": $StructureProcessorType<$GravityProcessor>
static readonly "JIGSAW_REPLACEMENT": $StructureProcessorType<$JigsawReplacementProcessor>
static readonly "LAVA_SUBMERGED_BLOCK": $StructureProcessorType<$LavaSubmergedBlockProcessor>
static readonly "LIST_CODEC": $Codec<$Holder<$StructureProcessorList>>
static readonly "LIST_OBJECT_CODEC": $Codec<$StructureProcessorList>
static readonly "NOP": $StructureProcessorType<$NopProcessor>
static readonly "PROTECTED_BLOCKS": $StructureProcessorType<$ProtectedBlockProcessor>
static readonly "RULE": $StructureProcessorType<$RuleProcessor>
static readonly "SINGLE_CODEC": $Codec<$StructureProcessor>

static "register"<P extends $StructureProcessor>(string0: string, codec1: $Codec$$Type<P>): $StructureProcessorType<P>
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureProcessorType$$Type<P extends $StructureProcessor> = ($StructureProcessorType<P> | Special.WorldgenStructureProcessor | (() => $Codec$$Type<P>));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureProcessorType_<P extends $StructureProcessor> = $StructureProcessorType$$Type<P>;
}
}

declare module "packages/net/minecraft/world/level/levelgen/structure/$StructureStart" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $StructureStart$$Type = ($StructureStart);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $StructureStart_ = $StructureStart$$Type;
}
}

