declare module "packages/net/minecraft/world/damagesource/$DamageSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DamageSource$$Type = ($DamageSource);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DamageSource_ = $DamageSource$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$FallLocation" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $FallLocation$$Type = ($FallLocation);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $FallLocation_ = $FallLocation$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$CombatTracker" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CombatTracker$$Type = ($CombatTracker);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CombatTracker_ = $CombatTracker$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$DamageSources" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DamageSources$$Type = ($DamageSources);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DamageSources_ = $DamageSources$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$DeathMessageType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DeathMessageType$$Type = ($DeathMessageType | ("default" | "fall_variants" | "intentional_game_design"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DeathMessageType_ = $DeathMessageType$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$DamageType" {
import { $Record } from "packages/java/lang/$Record"
import { $DeathMessageType, $DeathMessageType$$Type } from "packages/net/minecraft/world/damagesource/$DeathMessageType"
import { $DamageEffects, $DamageEffects$$Type } from "packages/net/minecraft/world/damagesource/$DamageEffects"
import { $DamageScaling, $DamageScaling$$Type } from "packages/net/minecraft/world/damagesource/$DamageScaling"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $DamageType extends $Record {
static readonly "CODEC": $Codec<$DamageType>

constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float, damageEffects3: $DamageEffects$$Type, deathMessageType4: $DeathMessageType$$Type)
constructor(string0: string, float1: float)
constructor(string0: string, float1: float, damageEffects2: $DamageEffects$$Type)
constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float, damageEffects3: $DamageEffects$$Type)
constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float)

public "deathMessageType"(): $DeathMessageType
public "effects"(): $DamageEffects
public "exhaustion"(): float
public "msgId"(): string
public "scaling"(): $DamageScaling
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.DamageType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.DamageTypeTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DamageType$$Type = ($DamageType | Special.DamageType);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DamageType_ = $DamageType$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$DamageScaling" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DamageScaling$$Type = ($DamageScaling | ("never" | "when_caused_by_living_non_player" | "always"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DamageScaling_ = $DamageScaling$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$CombatEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $CombatEntry$$Type = ($CombatEntry);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $CombatEntry_ = $CombatEntry$$Type;
}
}

declare module "packages/net/minecraft/world/damagesource/$DamageEffects" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $DamageEffects$$Type = ($DamageEffects | ("hurt" | "thorns" | "drowning" | "burning" | "poking" | "freezing"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $DamageEffects_ = $DamageEffects$$Type;
}
}

