declare module "packages/net/minecraft/sounds/$SoundSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SoundSource$$Type = ($SoundSource | ("master" | "music" | "records" | "weather" | "blocks" | "hostile" | "neutral" | "players" | "ambient" | "voice"));
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SoundSource_ = $SoundSource$$Type;
}
}

declare module "packages/net/minecraft/sounds/$SoundEvent" {
import { $Holder } from "packages/net/minecraft/core/$Holder"
import { $FriendlyByteBuf$$Type } from "packages/net/minecraft/network/$FriendlyByteBuf"
import { $ResourceLocation, $ResourceLocation$$Type } from "packages/net/minecraft/resources/$ResourceLocation"
import { $Codec } from "packages/com/mojang/serialization/$Codec"

export class $SoundEvent {
static readonly "CODEC": $Codec<$Holder<$SoundEvent>>
static readonly "DIRECT_CODEC": $Codec<$SoundEvent>

public static "createFixedRangeEvent"(resourceLocation0: $ResourceLocation$$Type, float1: float): $SoundEvent
public static "createVariableRangeEvent"(resourceLocation0: $ResourceLocation$$Type): $SoundEvent
public "getLocation"(): $ResourceLocation
public "getRange"(float0: float): float
public static "readFromNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): $SoundEvent
public "writeToNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): void
get "location"(): $ResourceLocation
set "location"(value: $ResourceLocation$$Type)
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.SoundEvent
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.SoundEventTag
}
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $SoundEvent$$Type = ($SoundEvent | Special.SoundEvent);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $SoundEvent_ = $SoundEvent$$Type;
}
}

declare module "packages/net/minecraft/sounds/$Music" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Class-specific type exported by ProbeJS, use global `{Type}_` types for convenience unless there's a naming conflict. */
export type $Music$$Type = ($Music);
/** Global type exported for convenience, use class-specific types if there's a naming conflict. */
declare global {
export type $Music_ = $Music$$Type;
}
}

